import assert from 'node:assert/strict';
import * as M from './model.js';
import * as C from './combat.js';
import {emitCombatEvent,combatEventsAfter} from './combat-events.js';
import {ArenaRenderer,drawDungeon,arenaTheme} from './arena.js';
let passed=0;function test(name,fn){fn();console.log('PASS',name);passed++;}
function fixture(){const s=M.makeGame('Arena Academy',1000000,881);M.openFoundation(s);for(const w of s.applicants.slice(0,3))M.recruit(s,w.id);return s;}
function start(s){C.startExpedition(s,s.wizards.map(w=>w.id),1);if(s.combat.state==='choice')C.roomChoice(s,'risk');return s.combat;}
test('Actual damage has source and target; visual events do not enter saves',()=>{const s=fixture(),c=start(s);for(let i=0;i<8;i++)C.stepCombat(s,.125);const e=combatEventsAfter(c).find(e=>e.kind==='projectile');assert.ok(e);assert.ok([...c.heroes,...c.enemies].some(a=>a.id===e.sourceId));assert.ok(Number.isFinite(e.amount));assert.equal(combatEventsAfter(M.clone(s).combat).length,0);});
test('Healing targets an injured ally and summoning creates a visible entity',()=>{const s=fixture();for(const [idx,family] of ['restoration','necromancy'].entries()){const it=M.item(s,1);it.family=family;it.slot='focus';it.tier=1;M.equip(s,s.wizards[idx],it.id);s.runes[family]=30;}s.wizards[2].hp=40;const c=start(s);C.stepCombat(s,.125);const es=combatEventsAfter(c);assert.ok(es.some(e=>e.kind==='heal'&&e.sourceId===s.wizards[0].id&&e.targetId===s.wizards[2].id));assert.ok(es.some(e=>e.kind==='summon'&&c.summons.some(a=>a.id===e.targetId)));});
test('Visual movement is finite, bounded, and never mutates simulation',()=>{const s=fixture(),c=start(s),r=new ArenaRenderer(),before=JSON.stringify(s);for(let i=0;i<600;i++)r.sync(c,s.wizards,340,400,1/60);assert.equal(JSON.stringify(s),before);for(const a of r.actors.values()){assert.ok(Number.isFinite(a.x)&&Number.isFinite(a.y));assert.ok(a.x>0&&a.x<1&&a.y>0&&a.y<1);}});
test('Hitsplats wait for impact and sequential damage cannot reverse displayed HP',()=>{const s=fixture(),c=start(s),r=new ArenaRenderer();r.sync(c,s.wizards,340,400,1/60);const target=c.enemies[0],hp=target.hp;emitCombatEvent(c,{kind:'projectile',sourceId:c.heroes[0].id,targetId:target.id,family:'fire',amount:5,hpBefore:hp,hpAfter:hp-5});emitCombatEvent(c,{kind:'tick',sourceId:c.heroes[0].id,targetId:target.id,family:'fire',amount:hp-5,hpBefore:hp-5,hpAfter:0});target.hp=0;r.sync(c,s.wizards,340,400,1/60);assert.equal(r.splats.length,0);assert.equal(r.actors.get(target.id).hp,hp);for(let i=0;i<65;i++)r.sync(c,s.wizards,340,400,1/60);assert.equal(r.splats.length,2);assert.equal(r.actors.get(target.id).hp,0);assert.notEqual(r.actors.get(target.id).deathAt,null);});
test('Event buffer stays bounded; reopening skips historical effects',()=>{const s=fixture(),c=start(s);for(let i=0;i<1000;i++)emitCombatEvent(c,{kind:'phase',targetId:c.enemies[0].id});assert.equal(combatEventsAfter(c).length,160);const r=new ArenaRenderer();r.reset(c,true);r.sync(c,s.wizards,340,400,1/60);assert.equal(r.phaseUntil,0);});
test('All dungeon themes draw finite geometry at phone and tablet sizes',()=>{const gradient={addColorStop(){}};const ctx=new Proxy({},{get(_,key){if(key==='createRadialGradient'||key==='createLinearGradient')return ()=>gradient;return (...args)=>{for(const a of args)if(typeof a==='number')assert.ok(Number.isFinite(a),key);};},set(){return true;}});for(const floor of [1,11,21,31,41])for(const [w,h] of [[306,400],[700,460]])drawDungeon(ctx,w,h,{floor,boss:false});assert.deepEqual(arenaTheme(1),arenaTheme(51));});
console.log(`${passed} arena tests passed.`);
