import {skillXP,skillLevel,initializeWizard} from './progression.js';
import {rnd,news,year} from './model.js';
import {DAY} from './data.js';
export const CAREER_JOBS={foraging:{skill:'Foraging',room:'garden',label:'Gather wild herbs'},mining:{skill:'Mining',room:'training',label:'Prospect mana crystals'},woodcutting:{skill:'Woodcutting',room:'garden',label:'Harvest enchanted timber'},alchemy:{skill:'Alchemy',room:'garden',label:'Brew forest potions'},smithing:{skill:'Smithing',room:'training',label:'Refine goblin scrap'},enchanting:{skill:'Enchanting',room:'runes',label:'Bind enchantments'},cooking:{skill:'Cooking',room:'garden',label:'Prepare field rations'},teaching:{skill:'Teaching',room:'training',label:'Teach apprentices'}};
const RECIPES={alchemy:{cost:{'Wild Herbs':3},output:'potions',amount:1,level:5},smithing:{cost:{'Goblin Scrap':2},output:'ingredients',amount:1,level:5},enchanting:{cost:{'Wisp Essence':2,'Mana Crystal':1},output:'blanks',amount:2,level:20},cooking:{cost:{'Raw Meat':2},output:'Cooked Rations',amount:2,level:1}};
export function careerWork(s,dt){for(const w of s.wizards){const def=CAREER_JOBS[w.job];if(!def||w.status!=='Active'||s.expedition?.ids.includes(w.id))continue;initializeWizard(w);w.careerProgress=(w.careerProgress||0)+dt;let loops=0;while(w.careerProgress>=240000&&loops++<180){w.careerProgress-=240000;const level=skillLevel(w,def.skill),materials=s.materials||(s.materials={});skillXP(s,w,def.skill,12);if(w.job==='foraging'){materials['Wild Herbs']=(materials['Wild Herbs']||0)+1+(level>=20?1:0);if(level>=50&&rnd(s)<.1)materials.Moonbloom=(materials.Moonbloom||0)+1;}
 else if(w.job==='mining'){materials['Mana Crystal']=(materials['Mana Crystal']||0)+1;if(level>=30&&rnd(s)<.25)materials['Goblin Scrap']=(materials['Goblin Scrap']||0)+1;}
 else if(w.job==='woodcutting'){materials['Treant Bark']=(materials['Treant Bark']||0)+1;if(level>=40&&rnd(s)<.15)materials['Ancient Sap']=(materials['Ancient Sap']||0)+1;}
 else if(RECIPES[w.job]){const recipe=RECIPES[w.job];if(level<recipe.level)continue;if(Object.entries(recipe.cost).some(([key,n])=>(materials[key]||0)<n))continue;for(const [key,n] of Object.entries(recipe.cost))materials[key]-=n;if(recipe.output==='Cooked Rations')materials[recipe.output]=(materials[recipe.output]||0)+recipe.amount+(level>=50?1:0);else s[recipe.output]+=recipe.amount+(level>=60?1:0);}
 else if(w.job==='teaching'){s.reputation.Academic=Math.min(100,(s.reputation.Academic||0)+.01);}
 }}}
export function recordReputation(s,key,amount){s.reputation||={};s.reputation[key]=Math.max(-100,Math.min(100,(s.reputation[key]||0)+amount));}
export function rivalYear(s){if(!s.league?.schools?.length)return;const schools=s.league.schools.filter(x=>x.id!=='player');for(const school of schools){const personality=school.personality||'earnest';school.institution||={Dungeon:0,Research:0,Rift:0,Safety:50,Alchemy:0,Wealth:10,notables:[],headlines:[]};const st=school.institution,focus=({morbid:'Dungeon',reckless:'Dungeon',analytical:'Research',wealthy:'Wealth',patient:'Safety',gentle:'Safety',military:'Dungeon',ancient:'Research',homely:'Alchemy'})[personality]||'Rift';st[focus]=Math.min(100,(st[focus]||0)+1+rnd(s)*2);st.Rift=Math.min(100,st.Rift+(.2+school.league*.25));if(focus==='Dungeon'){school.depth=(school.depth||0)+(rnd(s)<.45?1:0);if(personality==='reckless')st.Safety=Math.max(0,st.Safety-.5);}const roster=school.roster||[],star=roster.length?roster[Math.floor(rnd(s)*roster.length)]:null;if(star&&rnd(s)<.08){const title=focus==='Dungeon'?'Dungeon explorer':focus==='Research'?'Scholar':focus==='Alchemy'?'Alchemist':focus==='Safety'?'Warden':focus==='Wealth'?'Patron':'Rift veteran';st.notables.unshift({name:star.name,title,year:year(s),wizardId:star.id});st.notables=st.notables.slice(0,5);}if(star&&rnd(s)<.035){const text=focus==='Dungeon'?`${school.name} reports a dangerous expedition led by ${star.name} at depth ${school.depth||1}.`:focus==='Research'?`${star.name} publishes a magical study at ${school.name}.`:focus==='Rift'?`${star.name} becomes the name to watch in ${school.name}'s Rift program.`:`${school.name} draws attention for ${focus.toLowerCase()} under ${star.name}.`;const e={year:year(s),school:school.id,name:school.name,wizard:star.name,text,kind:focus};st.headlines.unshift(e);st.headlines=st.headlines.slice(0,4);s.rivalHistory||=[];s.rivalHistory.unshift(e);s.rivalHistory=s.rivalHistory.slice(0,35);news(s,text,'rival');}}
}
