import {practiceMagic,checkAmbition} from './progression.js';
import {emitCombatEvent} from './combat-events.js';
import {FAMILIES,BOSSES,ENEMIES,TRAITS,INJURIES} from './data.js';
import {rnd,pick,integer,uid,year,active,attributes,stat,gainXP,item,archive,news,die,refreshRecords,checkAchievements} from './model.js';
export const bossFor=f=>BOSSES[(Math.floor(f/10)-1+10000)%BOSSES.length];
export function startExpedition(s,ids,floor=s.depth+1,automated=false){if(s.expedition)throw Error('An expedition is already outside.');const ws=ids.map(id=>s.wizards.find(w=>w.id===id)).filter(w=>w?.status==='Active'&&!w.injury);if(!ws.length||ws.length>3||new Set(ids).size!==ids.length||ws.length!==ids.length)throw Error('Choose one to three healthy active wizards.');if(floor>s.depth+1||floor<1)throw Error('That floor is not accessible.');if(automated&&floor>s.depth)throw Error('Unknown floors cannot be automated.');if(floor%10===0&&s.seals<1)throw Error('Every boss attempt requires a Boss Seal.');for(const w of ws){const a=attributes(s,w);if(w.hp==null)w.hp=a.hp;if(w.mana==null)w.mana=a.mana;if(w.hp<a.hp*.25)throw Error(`${w.name} needs to recover first.`);}s.expedition={ids:ws.map(w=>w.id),floor,cleared:0,automated,started:s.time};for(const w of ws)stat(s,w,'expeditions');enterFloor(s,floor,automated);}
export function enterFloor(s,floor,automated=false){const ex=s.expedition;if(!ex)throw Error('No expedition.');if(s.combat?.state==='fighting')throw Error('The current fight is not finished.');if(s.combat?.state==='choice')throw Error('Resolve this chamber first.');if(floor>s.depth+1)throw Error('Clear the previous floor first.');if(floor%10===0){if(s.seals<1)throw Error('You need a Boss Seal.');s.seals--;for(const id of ex.ids){const w=s.wizards.find(w=>w.id===id&&w.status==='Active');if(w)stat(s,w,'bossAttempts');}}ex.floor=floor;const boss=floor%10===0,b=bossFor(floor),kind=boss?'boss':automated?'normal':pick(s,['normal','normal','normal','elite','hazard','treasure','shrine','strange']);const heroes=ex.ids.map(id=>s.wizards.find(w=>w.id===id&&w.status==='Active')).filter(Boolean).map(w=>{const a=attributes(s,w);return {id:w.id,name:w.name,hp:Math.min(w.hp,a.hp),maxHP:a.hp,mana:Math.min(w.mana,a.mana),maxMana:a.mana,power:a.power,defense:a.defense,position:w.position,status:{},barrier:0,cd:.3,spellCD:0,taunt:0,side:'hero',color:w.color};});
 const c={id:uid(s,'fight'),floor,kind,boss,mechanic:boss?b.mechanic:null,state:['treasure','shrine','strange'].includes(kind)?'choice':'fighting',heroes,enemies:[],summons:[],log:[],time:0,speed:1,phase:1,fx:[],choiceResolved:false};const n=boss?1:kind==='elite'?2:integer(s,2,3);for(let i=0;i<n;i++){const hp=(22+floor*10)*Math.pow(1.012,floor)*(boss?7:kind==='elite'?1.8:1);c.enemies.push({id:`e${i}`,name:boss?b.name:pick(s,ENEMIES),hp:Math.round(hp),maxHP:Math.round(hp),power:(3+floor*1.5)*Math.pow(1.008,floor)*(boss?1.45:kind==='elite'?1.3:1),defense:floor*.3,cd:1+i*.35,status:{},barrier:0,side:'enemy',assassin:!boss&&rnd(s)<.12});}s.combat=c;log(c,boss?`${b.name}: ${b.hint}`:`Floor ${floor} · ${kind==='normal'?'an unwelcome reception':kind}`);if(kind==='hazard'){for(const h of heroes)h.hp=Math.max(1,h.hp-h.maxHP*.12);log(c,'A pressure glyph removes 12% of the party’s maximum HP.');}return c;}
function log(c,text){c.log.push({t:Math.round(c.time*10)/10,text});c.log=c.log.slice(-180);}
export function roomChoice(s,choice){const c=s.combat;if(!c||c.state!=='choice'||c.choiceResolved)return;c.choiceResolved=true;if(c.kind==='shrine'){if(choice==='rest'){for(const h of c.heroes){h.hp=Math.min(h.maxHP,h.hp+h.maxHP*.22);h.mana=Math.min(h.maxMana,h.mana+h.maxMana*.18);}log(c,'The shrine accepts silence as payment.');clearFloor(s,false);return;}if(s.gold>=30){s.gold-=30;for(const h of c.heroes)h.barrier+=h.maxHP*.3;log(c,'An offering purchases a strong barrier.');}c.state='fighting';return;}if(c.kind==='treasure'){if(choice==='safe'){s.gold+=20+c.floor*4;log(c,'A modest chest, mercifully free of teeth.');clearFloor(s,false);return;}log(c,'The larger chest contains a larger problem.');c.enemies[0].name='Treasury Mimic';c.enemies[0].hp*=1.4;c.enemies[0].maxHP=c.enemies[0].hp;c.kind='elite';c.guaranteedLoot=true;}else{if(choice==='safe'){log(c,'You leave the impossible room undisturbed.');clearFloor(s,false);return;}for(const h of c.heroes)h.mana=Math.max(0,h.mana-8);c.guaranteedLoot=true;log(c,'An investigation costs mana. The discovery may be worth it.');}c.state='fighting';}
function livingH(c){return c.heroes.filter(h=>h.hp>0);}
function livingE(c){return c.enemies.filter(h=>h.hp>0);}
function damage(s,c,target,amount,source,w=null,ability='Magic Missile',visualSource=null){if(target.hp<=0)return 0;const hpBefore=target.hp;let critical=false,echoAmount=0;let val=Math.max(1,amount*(100/(100+target.defense*(target.status.Curse?.left>0?3:4))));const a=w?attributes(s,w):null;if(a&&rnd(s)<a.crit){val*=1.65;critical=true;stat(s,w,'crits');}if(a?.affixes.includes('conduit')&&Object.keys(target.status).length)val*=1.25;const absorbed=Math.min(target.barrier||0,val);target.barrier=Math.max(0,(target.barrier||0)-absorbed);val=Math.round(Math.max(0,val-absorbed));const actual=Math.min(target.hp,val);target.hp=Math.max(0,target.hp-val);if(w){stat(s,w,'damage',actual);w.stats.largestHit=Math.max(w.stats.largestHit||0,val);s.stats.largestHit=Math.max(s.stats.largestHit||0,val);if(a.affixes.includes('vampire')){const hero=c.heroes.find(h=>h.id===w.id);if(hero?.hp>0)heal(s,c,hero,actual*.12,w,false);}if(a.affixes.includes('echo')&&rnd(s)<.18&&target.hp>0){const echo=Math.min(target.hp,Math.round(val*.45));target.hp-=echo;echoAmount=echo;stat(s,w,'damage',echo);}}
 const sourceEntity=[...c.heroes,...c.enemies,...c.summons].find(x=>x.id===visualSource)||[...c.heroes,...c.enemies,...c.summons].find(x=>x.name===source)||c.heroes.find(x=>x.id===w?.id);
 const spellFamily=FAMILIES.find(f=>f.spell===ability)?.id||({Burn:'fire',Poison:'nature',Bleed:'shadow',Curse:'arcane','Summon strike':'necromancy','Final Detonation':'fire'})[ability]||(sourceEntity?.side==='enemy'?'hostile':'missile');
 emitCombatEvent(c,{kind:['Burn','Poison','Bleed','Curse'].includes(ability)?'tick':ability==='Final Detonation'?'explosion':ability==='Summon strike'?'strike':'projectile',sourceId:sourceEntity?.id||target.id,targetId:target.id,family:spellFamily,ability,amount:actual,absorbed:Math.round(absorbed),critical,hpBefore,hpAfter:target.hp,echoAmount});
 if(target.side==='hero'){const tw=s.wizards.find(w=>w.id===target.id);stat(s,tw,'taken',actual);}c.fx.push({id:uid(s,'fx'),target:target.id,text:`−${val}`,kind:'damage',at:c.time});c.fx=c.fx.slice(-12);if(actual>0)log(c,`${source} → ${target.name}: ${Math.round(actual)} · ${ability}`);
 if(target.hp<=0){emitCombatEvent(c,{kind:'death',targetId:target.id,sourceId:sourceEntity?.id||target.id});log(c,`${target.name} falls.`);if(target.side==='enemy'&&w){stat(s,w,'kills');if(a.affixes.includes('renewal')){const h=c.heroes.find(h=>h.id===w.id);if(h)h.mana=Math.min(h.maxMana,h.mana+3);}if(c.kind==='elite')stat(s,w,'eliteKills');}if(target.side==='hero')killWizard(s,c,target);if(target.side==='summon'&&target.volatile){for(const e of livingE(c))damage(s,c,e,target.power*1.8,target.name,s.wizards.find(w=>w.id===target.owner),'Final Detonation',target.id);}}
 return actual;}
function heal(s,c,h,n,w,barrier=true){if(h.hp<=0)return;const amount=Math.round(n*(TRAITS[w.trait][2]==='healing'?1.2:1));const actual=Math.min(h.maxHP-h.hp,amount);if(h.hp<h.maxHP*.25&&actual>h.maxHP*.2)stat(s,w,'saved');h.hp+=actual;stat(s,w,'healing',actual);stat(s,w,'overhealing',amount-actual);if(barrier&&attributes(s,w).affixes.includes('mercy'))h.barrier+=amount*.25;if(actual>0){emitCombatEvent(c,{kind:'heal',sourceId:w.id,targetId:h.id,family:'restoration',ability:'Second Breath',amount:actual,hpBefore:h.hp-actual,hpAfter:h.hp});c.fx.push({id:uid(s,'fx'),target:h.id,text:`+${actual}`,kind:'heal',at:c.time});log(c,`${w.name} heals ${h.name} for ${actual}.`);}}
function killWizard(s,c,h){const w=s.wizards.find(w=>w.id===h.id);if(!w||w.status==='Deceased')return;const ids=Object.values(w.equipment).filter(Boolean),items=s.items.filter(i=>ids.includes(i.id));for(const it of items){it.owner=null;it.lostFloor=c.floor;archive(s,'items',it.id,it);}s.items=s.items.filter(i=>!ids.includes(i.id));if(items.length){s.lost.push({id:uid(s,'cache'),floor:c.floor,year:year(s),names:[w.name],items,cost:Math.round(60+c.floor*18+items.reduce((n,i)=>n+i.value,0)*.18),ready:0});}w.equipment={focus:null,robe:null,charm:null};die(s,w,`dungeon floor ${c.floor}`);}
function cast(s,c,h,w){const a=attributes(s,w),allies=livingH(c),enemies=livingE(c);if(!enemies.length)return false;const candidates=a.items.slice().sort((a,b)=>{const f=FAMILIES.find(f=>f.id===a.family),g=FAMILIES.find(f=>f.id===b.family);return (g.kind==='heal'?10:0)-(f.kind==='heal'?10:0);});for(const it of candidates){const f=FAMILIES.find(f=>f.id===it.family),injured=allies.slice().sort((a,b)=>a.hp/a.maxHP-b.hp/b.maxHP)[0],cost=Math.round((5+it.tier*3)*(a.affixes.includes('efficient')?.8:1)),rkey=it.family+(it.tier>1?it.tier:'');if(h.mana<cost||(s.runes[rkey]||0)<it.charges)continue;if(w.directive==='Conservative'&&h.mana<h.maxMana*.5&&f.kind!=='heal')continue;if(w.directive==='Support'&&!['heal','shield','summon'].includes(f.kind)&&allies.some(x=>x.hp<x.maxHP*.6))continue;if(f.kind==='heal'&&(!injured||injured.hp>injured.maxHP*(w.directive==='Support'?.92:.78)))continue;if(f.kind==='shield'&&allies.every(x=>x.barrier>x.maxHP*.15))continue;const summons=c.summons.filter(x=>x.owner===w.id&&x.hp>0),limit=1+(a.affixes.includes('swarms')?1:0);if(f.kind==='summon'&&summons.length>=limit)continue;
 h.mana-=cost;if(!(TRAITS[w.trait][2]==='frugal'&&rnd(s)<.2))s.runes[rkey]-=it.charges;stat(s,w,'spells');practiceMagic(s,w,it.family,2);const power=h.power*(1+it.tier*.2)*(h.status.Blessing?.left>0?1.12:1);log(c,`${w.name} casts ${f.spell}.`);
 if(f.kind==='heal'){heal(s,c,injured,power*2,w);delete injured.status.Poison;delete injured.status.Curse;}
 else if(f.kind==='shield'){const target=allies.slice().sort((a,b)=>a.hp/a.maxHP-b.hp/b.maxHP)[0];target.barrier+=power*2;h.taunt=5;emitCombatEvent(c,{kind:'shield',sourceId:w.id,targetId:target.id,family:'barrier',ability:f.spell,amount:Math.round(power*2)});}
 else if(f.kind==='summon'){const mult=(a.affixes.includes('legacy')?1.3:1)*(TRAITS[w.trait][2]==='summon'?1.2:1);c.summons.push({id:uid(s,'summon'),name:it.rarity>=4?'Grave Marshal':'Bone Custodian',owner:w.id,hp:power*2*mult,maxHP:power*2*mult,power:power*.65*mult,defense:2,cd:.5,side:'summon',status:{},barrier:0,volatile:a.affixes.includes('volatile')});stat(s,w,'summons');emitCombatEvent(c,{kind:'summon',sourceId:w.id,targetId:c.summons.at(-1).id,family:'necromancy',ability:f.spell});}
 else{const targets=f.kind==='aoe'?enemies:it.family==='shadow'?[enemies.at(-1)]:[enemies[0]];for(const e of targets){damage(s,c,e,power*(f.kind==='aoe'?1.15:1.85),w.name,w,f.spell);if(e.hp>0&&f.status!=='Blessing'){e.status[f.status]={left:6,power:power*.15,owner:w.id,tick:0};stat(s,w,'statuses');}}if(it.family==='radiant'){heal(s,c,injured,power*.35,w);for(const ally of allies)ally.status.Blessing={left:6,power:0,tick:0};}}
 h.spellCD=(w.directive==='Aggressive'?3:4.5)*(a.affixes.includes('haste')?.85:1);return true;}
 return false;}
export function stepCombat(s,dt){const c=s.combat;if(!c||c.state!=='fighting')return;dt=Math.min(.5,Math.max(0,dt));c.time+=dt;for(const x of [...c.heroes,...c.enemies,...c.summons]){if(x.hp<=0)continue;for(const [key,st] of Object.entries(x.status)){st.left-=dt;st.tick=(st.tick||0)+dt;if(st.tick>=1&&['Burn','Poison','Bleed','Curse'].includes(key)){st.tick-=1;const owner=s.wizards.find(w=>w.id===st.owner);damage(s,c,x,st.power,key,owner,key);}if(st.left<=0)delete x.status[key];}x.cd-=dt*(x.status.Slow?.left>0?.65:x.status.Shock?.left>0?.8:1);if(x.side==='hero'){x.spellCD-=dt;x.taunt=Math.max(0,x.taunt-dt);}}
 for(const h of livingH(c)){if(!livingE(c).length)break;const w=s.wizards.find(w=>w.id===h.id);if(h.spellCD<=0&&cast(s,c,h,w))h.cd=Math.max(h.cd,.8);else if(h.cd<=0){damage(s,c,livingE(c)[0],h.power*(h.status.Blessing?.left>0?1.12:1),w.name,w);stat(s,w,'spells');practiceMagic(s,w,'arcane',.3);h.cd=1.6;}}
 for(const su of c.summons.filter(x=>x.hp>0)){if(su.cd<=0&&livingE(c).length){const w=s.wizards.find(w=>w.id===su.owner);const target=livingE(c)[0];damage(s,c,target,su.power,su.name,w,'Summon strike',su.id);if(target.hp<=0&&w)stat(s,w,'summonKills');su.cd=1.8;}}
 for(const e of livingE(c)){if(e.cd>0||!livingH(c).length)continue;const hs=livingH(c),ss=c.summons.filter(x=>x.hp>0),taunt=hs.find(h=>h.taunt>0);let targets;if(c.boss&&['storm','poison'].includes(c.mechanic)&&c.phase>=2){targets=hs;}else if(taunt)targets=[taunt];else if(ss.length&&rnd(s)<.55)targets=[ss[0]];else if(e.assassin||c.mechanic==='assassin')targets=[hs.slice().sort((a,b)=>['Back','Middle','Front'].indexOf(a.position)-['Back','Middle','Front'].indexOf(b.position))[0]];else{const sorted=hs.slice().sort((a,b)=>['Front','Middle','Back'].indexOf(a.position)-['Front','Middle','Back'].indexOf(b.position));targets=[rnd(s)<.72?sorted[0]:pick(s,sorted)];}for(const t of targets){damage(s,c,t,e.power*(c.mechanic==='enrage'&&c.time>30?1.8:1)*(c.phase===2?1.2:1)/(targets.length>1?1.3:1),e.name,null,'Magic Missile',e.id);if(t.side==='hero'&&c.mechanic==='drain')t.mana=Math.max(0,t.mana-3);if(c.mechanic==='poison')t.status.Poison={left:6,power:e.power*.15,tick:0};}e.cd=c.boss?2.1:2.6;}
 if(c.boss&&c.phase===1&&c.enemies[0].hp<c.enemies[0].maxHP*.5){c.phase=2;emitCombatEvent(c,{kind:'phase',targetId:c.enemies[0].id,family:'arcane',ability:'Phase II'});log(c,'PHASE II — the chamber changes.');if(c.mechanic==='mirror')c.enemies[0].barrier=c.enemies[0].maxHP*.2;if(c.mechanic==='summon'){for(let j=0;j<2;j++)c.enemies.push({id:uid(s,'add'),name:'Custodial Associate',hp:c.enemies[0].maxHP*.1,maxHP:c.enemies[0].maxHP*.1,power:c.enemies[0].power*.5,defense:2,cd:1,status:{},side:'enemy',barrier:0});}}
 syncVitals(s,c);if(!livingH(c).length){c.state='defeat';news(s,`Disaster on floor ${c.floor}. ${s.expedition.ids.map(id=>s.wizards.find(w=>w.id===id)?.name||'A wizard').join(', ')} never returned.`,'death');archive(s,'battles',c.id,c);s.expedition=null;checkAchievements(s);}else if(!livingE(c).length)clearFloor(s,true);else if(c.time>180){log(c,'An unstable chamber forces an emergency withdrawal.');returnHome(s,true);}}
function syncVitals(s,c){for(const h of c.heroes){const w=s.wizards.find(w=>w.id===h.id);if(w){w.hp=Math.max(0,h.hp);w.mana=Math.max(0,h.mana);}}}
export function clearFloor(s,fought=true){const c=s.combat;if(!c||c.state==='victory')return;c.state='victory';syncVitals(s,c);const survivors=c.heroes.filter(h=>h.hp>0).map(h=>s.wizards.find(w=>w.id===h.id));const gold=integer(s,10,20)+c.floor*5+(c.boss?c.floor*12:0);s.gold+=gold;s.blanks+=integer(s,1,4)+(c.boss?8:0);s.ingredients+=c.boss?3:rnd(s)<.65?1:0;if(rnd(s)<.16)s.potions++;if(c.boss&&fought)stat(s,null,'bossKills');const fresh=c.floor>s.depth;if(fresh){s.depth=c.floor;s.prestige+=c.boss?8:1;}s.expedition.cleared++;for(const w of survivors){stat(s,w,'floors');w.stats.depth=Math.max(w.stats.depth||0,c.floor);stat(s,w,'gold',gold/survivors.length);if(c.boss&&fought){w.stats.bossKills=(w.stats.bossKills||0)+1;w.yearStats.bossKills=(w.yearStats.bossKills||0)+1;}if(w.hp<attributes(s,w).hp*.2)stat(s,w,'nearDeath');gainXP(s,w,20+c.floor*3+(c.boss?80:0));checkAmbition(s,w);refreshRecords(s,w);}const luck=survivors.some(w=>TRAITS[w.trait][2]==='luck')?.05:0;let it=null;if(c.guaranteedLoot||rnd(s)<(c.boss?.38:.075)+luck)it=item(s,c.floor,c.boss,pick(s,survivors));c.reward={gold,fresh,item:it?.name||null,itemId:it?.id||null};for(const cache of s.lost.filter(x=>x.floor===c.floor&&!x.ready))recoverCache(s,cache);log(c,`Floor secured. +${gold} gold${it?` · ${it.name}`:''}. ${fresh?'Advance requires your decision.':''}`);if(c.boss)news(s,`${survivors.map(w=>w.name).join(', ')} defeated ${bossFor(c.floor).name} on floor ${c.floor}.`,'boss');archive(s,'battles',c.id,c);checkAchievements(s);}
export function returnHome(s,forced=false){const ex=s.expedition;if(!ex)return;const c=s.combat;if(c)syncVitals(s,c);for(const id of ex.ids){const w=s.wizards.find(w=>w.id===id&&w.status==='Active');if(!w)continue;if(c?.state==='fighting'){stat(s,w,'retreats');w.hp=Math.max(1,w.hp*(forced?.8:.9));}if(w.hp<attributes(s,w).hp*.3&&rnd(s)<.35){w.injury={name:pick(s,INJURIES),until:s.time+1800000};news(s,`${w.name} returns with ${w.injury.name}.`,'injury');}refreshRecords(s,w);}if(c&&c.state==='fighting'){c.state='retreat';archive(s,'battles',c.id,c);}s.expedition=null;}
export function recoverCache(s,cache){if(!s.lost.some(x=>x.id===cache.id))return;for(const it of cache.items){delete it.lostFloor;it.owner=null;s.items.push(it);archive(s,'items',it.id,it);}s.lost=s.lost.filter(x=>x.id!==cache.id);stat(s,null,'recoveries');news(s,`Recovered ${cache.items.length} heirlooms from floor ${cache.floor}, lost with ${cache.names.join(', ')}.`,'recovery');}
export function potion(s,w){if(s.combat?.state==='fighting'&&s.expedition?.ids.includes(w.id))throw Error('Prepare potions between floors. Combat is automated.');if(s.potions<1)throw Error('No potions remain.');s.potions--;const a=attributes(s,w);w.hp=Math.min(a.hp,w.hp+a.hp*.45);w.mana=Math.min(a.mana,w.mana+a.mana*.3);if(s.combat&&s.expedition?.ids.includes(w.id)){const h=s.combat.heroes.find(h=>h.id===w.id);if(h){h.hp=w.hp;h.mana=w.mana;}}stat(s,w,'potions');}
export function farm(s,job){if(s.expedition)return {skipped:true};const ws=active(s).filter(w=>w.job===job&&!w.injury&&w.hp>attributes(s,w).hp*.5).slice(0,3);if(!ws.length)return {skipped:true};const floor=job==='boss'?s.bossFloor:s.farmFloor;if(floor>s.depth||floor<1||job==='boss'&&(floor%10!==0||s.seals<1))return {skipped:true};const oldCombat=s.combat;startExpedition(s,ws.map(w=>w.id),floor,true);let steps=0;while(s.combat.state==='fighting'&&steps++<400)stepCombat(s,.5);const result=s.combat.state;returnHome(s);s.combat=oldCombat;return {result};}
