export const VERSION='1.3.0';
export const DAY=86400000, HOUR=3600000, CAP=12*HOUR;
export const FAMILIES=[
{id:'fire',name:'Ember',color:'#f49462',icon:'☀',spell:'Cinderburst',kind:'aoe',status:'Burn',sport:'Power'},
{id:'frost',name:'Rime',color:'#9fdde8',icon:'❄',spell:'Winterglass',kind:'attack',status:'Slow',sport:'Defense'},
{id:'storm',name:'Tempest',color:'#cebdff',icon:'ϟ',spell:'Chain Lightning',kind:'aoe',status:'Shock',sport:'Speed'},
{id:'restoration',name:'Mending',color:'#9be0af',icon:'✚',spell:'Second Breath',kind:'heal',status:'Blessing',sport:'Awareness'},
{id:'necromancy',name:'Grave',color:'#c0c697',icon:'☠',spell:'Raise Custodian',kind:'summon',status:'Curse',sport:'Defense'},
{id:'arcane',name:'Aether',color:'#a9bbff',icon:'✧',spell:'Reality Fracture',kind:'attack',status:'Curse',sport:'Control'},
{id:'nature',name:'Briar',color:'#aecf72',icon:'❧',spell:'Venom Orchard',kind:'aoe',status:'Poison',sport:'Awareness'},
{id:'shadow',name:'Umbral',color:'#c8a9d9',icon:'☾',spell:'Backpage Blade',kind:'attack',status:'Bleed',sport:'Speed'},
{id:'radiant',name:'Dawn',color:'#f4d68b',icon:'✵',spell:'Dawn Verdict',kind:'attack',status:'Blessing',sport:'Power'},
{id:'barrier',name:'Bastion',color:'#91c8c2',icon:'⬡',spell:'Living Rampart',kind:'shield',status:'Barrier',sport:'Defense'}];
export const RARITIES=['Common','Uncommon','Rare','Ultra Rare','Legendary','Mythic'];
export const RARITY_COLORS=['#d1c8b5','#9cca94','#86b8f6','#c3a0ef','#e7be73','#f297b1'];
export const FIRST='Agnes,Orin,Mabel,Silas,Elowen,Cedric,Juniper,Bram,Thea,Otis,Imogen,Felix,Winifred,Alaric,Mira,Edwin,Hazel,Lucian,Nora,Ambrose,Wren,Tobias,Isolde,Emrys,Pippa,Rufus,Opal,Rowan,Lydia,Casper,Violet,Arthur,Ada,Dorian,Beatrix,Finch,Greta,Idris,Maeve,Niles,Petra,Quill,Rhea,Soren,Tansy,Ulric,Vera,Wilbur,Xanthe,Yarrow,Zelda,Leander,Esme,Hugo,Flora,Gideon,Iris,Jasper,Lark,Milo,Nell,Oscar,Percy,Rosamund,Selene,Tristan,Una,Valentine,Walter,Yvette'.split(',');
export const LAST='Blackwood,Thistledown,Quill,Underbough,Ashworth,Mothwick,Goodweather,Graves,Brindle,Marrow,Holloway,Starglass,Pennywhistle,Flint,Crumb,Evernight,Spindle,Lowbridge,Foxglove,Inkpot,Widdershins,Wintermere,Brass,Sparrow,Thornfield,Locke,Mooncalf,Hush,Cloudfoot,Greymantle,Tallow,Barley,Stillwater,Crowe,Tealeaf,Nettlewick,Bellweather,Oddsock,Fenwick,Glass,Rook,Bramble,Thimble,Peat,Willowmere,Goldleaf,Crackle,Strange,Pike,Hearth'.split(',');
export const TRAITS=[['Meticulous','Production +15%', 'production',.15],['Reckless','Damage +12%, defense −8%','reckless',.12],['Steady','Defense +12%','defense',.12],['Empathetic','Healing +20%','healing',.2],['Restless','Sport speed +12%','speed',.12],['Bookish','Training +15%','training',.15],['Competitive','Sport power +12%','power',.12],['Gregarious','Relationships grow faster','social',.3],['Stubborn','HP +12%','hp',.12],['Sensitive','Mana +15%','mana',.15],['Night owl','Shadow damage +15%','shadow',.15],['Unflappable','Injuries heal 20% faster','recovery',.2],['Morbid','Summons +20% strength','summon',.2],['Lucky','Equipment chance +5%','luck',.05],['Frugal','Rune charge cost sometimes waived','frugal',.2],['Observant','Sport awareness +12%','awareness',.12]];
export const ROOMS=[
{id:'desk',name:'Front Desk',sub:'Admissions & administration',icon:'✒',cost:0,prestige:0},
{id:'dorm',name:'Dormitory',sub:'Wizards & equipment',icon:'☽',cost:0,prestige:0},
{id:'gate',name:'Belowstairs',sub:'Dungeon expeditions',icon:'◈',cost:0,prestige:0},
{id:'training',name:'Practice Hall',sub:'Training & instruction',icon:'⚔',cost:120,prestige:0},
{id:'runes',name:'Rune Chamber',sub:'Inscribe the impossible',icon:'⌘',cost:140,prestige:0},
{id:'storage',name:'The Strongroom',sub:'Equipment & supplies',icon:'▣',cost:0,prestige:0},
{id:'infirmary',name:'Infirmary',sub:'Treatment & recovery',icon:'✚',cost:180,prestige:3},
{id:'rift',name:'Arcane Rift',sub:'Five wizards. One aperture.',icon:'◎',cost:160,prestige:0},
{id:'archives',name:'The Archives',sub:'Nobody is forgotten',icon:'▤',cost:0,prestige:0},
{id:'hall',name:'Hall of Names',sub:'Legends & achievements',icon:'♜',cost:400,prestige:25},
{id:'garden',name:'Moon Garden',sub:'Potions & quiet company',icon:'❧',cost:260,prestige:12},
{id:'observatory',name:'Observatory',sub:'Research & discoveries',icon:'✧',cost:650,prestige:40}];
export const JOBS={rest:'Rest & socialize',training:'Adventure training',athletics:'Rift practice',blank:'Make unscribed runes',fire:'Ember inscription',frost:'Rime inscription',storm:'Tempest inscription',restoration:'Mending inscription',necromancy:'Grave inscription',arcane:'Aether inscription',nature:'Briar inscription',shadow:'Umbral inscription',radiant:'Dawn inscription',barrier:'Bastion inscription',seals:'Bind boss seals',recovery:'Infirmary patient',farm:'Cleared-floor patrol',boss:'Defeated-boss patrol',garden:'Brew potions',research:'Arcane research',clerical:'Administrative work'};
export const INJURIES=['singed eyebrows','concussion','damaged casting hand','magical exhaustion','cursed wound','ankle hex','spectral hiccups'];
export const LEAGUES=['JV League','Regional League','Grand League','Archmage League'];
const schoolRows=[
['Muckwater Institute of Magic','swamp','The mud is a tactical choice.'],['Copper Kettle College','homely','Tea first. Humiliation second.'],['Ragged Moon Academy','chaotic','We have misplaced our strategy.'],['Little Bell Collegium','earnest','Our budget is small. Our grudges are not.'],['Mossbridge School','patient','We can wait. You appear to be tiring.'],['Eastwick Annex','bureaucratic','Please initial your defeat here.'],['The Crooked Spire','sly','The referee saw nothing. A promising start.'],
['Saint Aurelia’s College of Arcane Excellence','proper','An instructive performance. For us, certainly.'],['Emberpeak Academy','reckless','If the scoreboard survives, it counts.'],['Grimhold War College','military','Your formation has been reviewed. Unfavorably.'],['Briarwell Seminary','gentle','We wish you a painless recovery.'],['Saltglass Institute','maritime','A little pressure and you all sink.'],['Iron Lantern Academy','stoic','Bring better defenses.'],['Velvet Hex Conservatory','theatrical','The audience deserved a closer contest.'],['Gallowsmere College','morbid','We prepared condolences. Just in case.'],
['The Celestial Conservatory','analytical','Our model allows a 3% chance of your dignity.'],['Wyrmwood Academy','ancient','We remember your school’s first embarrassment.'],['Gilded Owl Academy','wealthy','Would better equipment help? We have spares.'],['Ninefold Lyceum','analytical','Seven errors. Two of them interesting.'],['Thorn Crown College','proud','A crown is not issued for participation.'],['Ashen Mirror Institute','eerie','We have seen this loss before.'],['Highwater Collegium','maritime','You may wish to reconsider your depth.'],['Dusk Parliament','bureaucratic','The committee has approved our victory.'],
['Blackspire Academy','arrogant','We admire your affordable ambition.'],['Imperial Astrarium','regal','Your invitation was not a prediction.'],['Starfall Citadel','brilliant','Try looking up before the next goal.'],['Obsidian Choir','eerie','Your silence after that score was exquisite.'],['Crown of Glass','precise','Fragility is a design constraint. Yours.'],['Everfrost University','cold','Warm condolences on a cold performance.'],['The Last Meridian','patient','We have been here longer than your records.'],['Sovereign Hollow','arrogant','Do keep the souvenir program.']];
export const SCHOOLS=schoolRows.map((r,i)=>({id:'school'+(i+1),name:r[0],personality:r[1],quote:r[2],league:i<7?0:i<15?1:i<23?2:3}));
export const BOSSES=[
['The Unpaid Custodian','A mop with tenure.','grave','summon','The cleaning staff has unionized.'],
['Mother of Moths','A thousand wings drink spelllight.','nature','drain','Keep your mana close.'],
['The Glass Provost','Every fracture is a promotion.','frost','mirror','Barriers arrive at half health.'],
['Saint Zero','The absence of warmth has a name.','shadow','assassin','The rear line is not safe.'],
['The Copper Parliament','Seven opinions. One hammer.','storm','storm','A chamber-wide vote of no confidence.'],
['The Orchard Beneath','Its fruit remembers your name.','nature','poison','Poison accumulates every phase.'],
['The Deferred Emperor','Your appointment was centuries ago.','radiant','enrage','Damage rises after thirty seconds.'],
['Auditor of Souls','A discrepancy has been found.','necromancy','drain','Every spell requires supporting documents.'],
['The Hollow Star','Light that refuses to arrive.','arcane','storm','Stay together. Suffer together.'],
['The First Headmaster','The academy was built to keep something down.','barrier','mirror','Some records were sealed for a reason.']].map((x,i)=>({name:x[0],desc:x[1],family:x[2]==='grave'?'necromancy':x[2],mechanic:x[3],hint:x[4],drops:['Office of Ash','Unsigned Verdict','Last Bell','Borrowed Tomorrow','Quiet Rebellion','Final Examination'].map((n,j)=>({name:`${n} ${['Staff','Mantle','Signet'][j%3]}`,slot:['focus','robe','charm'][j%3],family:j%2?FAMILIES[(i+j)%10].id:(x[2]==='grave'?'necromancy':x[2])}))}));
export const ENEMIES=['Ink Slime','Tax Imp','Paper Wraith','Mildew Familiar','Clockwork Prefect','Lamprey Scholar','Dormitory Mimic','Grave Librarian','Briar Ghoul','Mirror Apprentice','Cinder Eel','Velvet Assassin','Rime Hound','Unlicensed Golem','Borrowed Skeleton','Thunder Mite','Cursed Proctor','Hollow Herald','Stairwell Serpent','Aether Leech'];
export const AFFIXES=[{id:'echo',name:'Echoing',desc:'18% chance to echo damage.',min:1},{id:'vampire',name:'Sanguine',desc:'Heal for 12% of damage dealt.',min:1},{id:'efficient',name:'Thrifty',desc:'Spell mana cost −20%.',min:0},{id:'swarms',name:'Crowded',desc:'Summon limit +1.',min:2},{id:'volatile',name:'Volatile',desc:'Fallen summons explode.',min:2},{id:'conduit',name:'Conductive',desc:'25% more damage against afflicted enemies.',min:1},{id:'mercy',name:'Merciful',desc:'Healing also grants a barrier.',min:2},{id:'haste',name:'Hasty',desc:'Spell cooldown −15%.',min:1},{id:'guardian',name:'Guardian',desc:'Defense +15%.',min:0},{id:'legacy',name:'Ancestral',desc:'Summon damage +30%.',min:3},{id:'renewal',name:'Renewing',desc:'Kills restore 3 mana.',min:2},{id:'critical',name:'Surgical',desc:'Critical chance +8%.',min:2}];
export const STATS={floors:'Floors cleared',depth:'Deepest floor',expeditions:'Expeditions',kills:'Enemies defeated',eliteKills:'Elite kills',bossAttempts:'Boss attempts',bossKills:'Boss kills',damage:'Damage dealt',taken:'Damage taken',largestHit:'Largest hit',healing:'Healing',overhealing:'Overhealing',saved:'Allies saved',summons:'Summons created',summonKills:'Summon kills',witnessed:'Deaths witnessed',nearDeath:'Near-death survivals',retreats:'Retreats',gold:'Gold recovered',lootValue:'Loot value',items:'Items found',potions:'Potions consumed',spells:'Spells cast',crits:'Critical hits',statuses:'Status effects',training:'Training hours',runes:'Runes manufactured',seals:'Seals bound',appearances:'Rift appearances',wins:'Rift wins',championships:'Championships',goals:'Rift goals',assists:'Rift assists',blocks:'Defensive stops',steals:'Rift steals',fouls:'Fouls',friendlyFire:'Teammates accidentally ignited',livestock:'Mistaken for livestock',incidents:'Unusual incidents',research:'Research completed'};
export const EVENT_LIBRARY=[
['The teapot has opinions','A faculty teapot demands a salary.','Negotiate a stipend',35,'gold',100,'Hire it as a filing assistant.','Drink ordinary water',0,'prestige',1],
['A door without a room','A new door appeared in the west wall. It is warm.','Fund an inspection',60,'blanks',35,'The room contained yesterday. And some runestones.','Brick it up',0,'gold',20],
['A very small dragon','It insists it is a visiting professor.','Offer a desk',50,'prestige',5,'It delivered an excellent lecture on hoarding.','Request credentials',0,'gold',30],
['The library migration','The books are moving south for winter.','Lay a trail of bookmarks',25,'prestige',3,'The books return. Mostly travel writing.','Let them stretch their spines',0,'blanks',8],
['Alumni in disguise','A masked visitor remembers a school that has not existed yet.','Hear their story',0,'prestige',4,'Some names were familiar. You wrote them down.','Offer supper',30,'potions',3],
['The annual inspection','An inspector has counted too many dimensions in the lavatory.','Pay for dimensional repairs',70,'prestige',6,'The fourth dimension is now staff only.','Submit an appeal',0,'gold',25],
['A friendly meteor','A warm stone lands politely in the garden.','Study the visitor',45,'ingredients',12,'It contains a rare mineral and a thank-you note.','Sell to a collector',0,'gold',100],
['The quiet bench','Someone has been leaving flowers at the memorial.','Build a proper garden bed',40,'prestige',5,'Nobody takes credit. Nobody needs to.','Leave a vase',0,'prestige',2],
['Rival hospitality','Muckwater sends a hamper. It is humming.','Open it outdoors',0,'potions',3,'The jam is exceptional. The lid is in orbit.','Return with compliments',0,'prestige',2],
['A scholarship petition','A bright applicant cannot afford travel.','Sponsor their journey',60,'applicant',1,'A new story begins at your front desk.','Send useful books',15,'prestige',2],
['An unclaimed inheritance','A lawyer offers a crate marked ABSOLUTELY NOT CURSED.','Accept the liability',75,'item',1,'The crate contains an interesting legal precedent.','Take the cash settlement',0,'gold',65],
['The impossible rehearsal','The choir has harmonized with a thunderstorm.','Bottle the encore',30,'blanks',24,'Only three windows were emotionally damaged.','End rehearsal early',0,'prestige',1],
['Socks in the rift','A rival accuses your team of enchanted hosiery.','Commission an investigation',40,'prestige',4,'The socks were ordinary. The feet were suspicious.','Issue a polite statement',0,'prestige',1],
['The moon owes us','The observatory discovers a billing error.','Send an invoice',20,'gold',145,'Payment arrived in an envelope of moonlight.','Publish the discovery',0,'prestige',4],
['A sleepwalking statue','The founder’s statue wanders into a lecture.','Enroll it',35,'prestige',4,'It has excellent attendance and terrible handwriting.','Guide it back',0,'ingredients',4],
['Time in a bottle','A merchant sells a bottle of unused Tuesday.','Buy the bottle',80,'runes',20,'It tastes like anticipation and administrative relief.','Decline politely',0,'prestige',1],
['The furnace apology','The furnace regrets several prior decisions.','Accept its apology',0,'gold',45,'Heating expenses fall. The furnace seems lighter.','Request a written statement',0,'prestige',3],
['An elective in courage','Students propose a trip to the forbidden cellar.','Chaperone the expedition',55,'item',1,'Courage is considerably safer with adult supervision.','Teach caution instead',0,'blanks',12],
['The haunted ledger','A former accountant is still balancing the books.','Give them closure',25,'prestige',5,'The final entry reads: Thank you.','Offer a consultancy',45,'gold',120],
['Chamber of compliments','The dungeon sends a flattering letter. Suspicious.','Arrange a cautious survey',50,'ingredients',15,'The trap was compliments. Nobody was prepared.','File under unsolicited',0,'gold',10],
['A missing constellation','Students find a star in the umbrella stand.','Return it to the sky',55,'prestige',7,'A new constellation resembles your crest.','Keep its shed starlight',0,'blanks',18],
['The tame catastrophe','A class experiment produces a perfectly behaved explosion.','Publish the method',30,'prestige',4,'The journal asks for fewer scorch marks.','License the discovery',0,'gold',65],
['Blackspire’s donation','A rival offers chairs embossed with its own crest.','Accept and reupholster',25,'gold',110,'The chairs are surprisingly comfortable.','Politely decline',0,'prestige',3],
['The long afternoon','Everyone is tired. Even the clocks.','Cancel classes for tea',40,'potions',5,'For an hour, nothing terrible happens.','Schedule a shorter break',0,'prestige',2],
['The sealed correspondence','A letter from the first academy waits below the gate.','Begin the investigation',50,'chain',1,'The handwriting matches an older door.','Preserve it in the archives',0,'prestige',3],
['An unusually large egg','It is ticking. The supplier insists this is intentional.','Study under supervision',70,'ingredients',18,'It hatched into a clock. A very hungry clock.','Return to sender',0,'gold',35],
['The apprentice fair','Young wizards display their thoroughly questionable inventions.','Sponsor a prize',55,'applicant',1,'The winner invented a safe version of the original invention.','Buy souvenir biscuits',10,'prestige',2],
['Rain going upward','Meteorology has become argumentative.','Install collection funnels',30,'blanks',22,'Gravity agrees to a temporary compromise.','Wait for clear weather',0,'prestige',1],
['A rival’s farewell','A neighboring academy has lost a beloved coach.','Send a memorial wreath',35,'prestige',5,'For one afternoon, there are no rivalries.','Send a handwritten letter',0,'prestige',2],
['The midnight market','A lantern-lit stall appears by the dungeon gate.','Buy a sealed relic',120,'item',1,'The seller remembers a former owner.','Trade mundane supplies',0,'gold',40]
];
export const CHAT={
rest:['The stairs moved again. I was almost on time.','I have filed a formal complaint against the soup.','I came here for a quiet education. An error.','Do you think the Headmaster reads these reports?','The door says push. It is lying.','We are technically accredited. In three dimensions.','Someone put a barrier on the biscuit tin.','I miss ordinary problems. Like wolves.','I think the furniture is judging us.','My hat has better attendance than I do.','There is a form for that. It has teeth.','A cloud followed me home. I named it Gerald.'],
training:['Magic Missile again? Fundamentals build character. Apparently.','My target has requested a transfer.','I was aiming at the other wall.','That was deliberate. The scream was not.','The instructor says I show potential. Potential liability.','One day this will be muscle memory. Today it is smoke.'],
runes:['This rune says FIRE. This one says FIR. Quite different.','We produce quality. Eventually.','If the rune hums, hum back. It feels included.','I have ink in a dimension I cannot reach.','Another hundred runes. Another suspicious thumbprint.','The unscribed ones are judging my handwriting.'],
rift:['Two Strikers, one Controller, two Wardens. No dragons.','Blackspire has silk practice robes. We have spite.','I could have scored that. In a different universe.','The aperture moved. That is my official statement.','Sport builds character. Mostly grievances.','I have memorized the rulebook. Both legal pages.'],
injury:['The infirmary says I am mostly original parts.','My casting hand has lodged an objection.','It only hurts when I remember the expedition.','The bandage is judging me.'],
boss:['We beat {boss}. I have been saying it all morning.','Management has interpreted our survival as evidence we are ready.','Floor {floor} was enough excitement for one lifetime.','Please tell me we are not going straight back.'],
loss:['An empty locker is louder than you think.','I still expect them at breakfast.','We should write down what happened. All of it.','Keep their staff safe, if we find it.'],
win:['We won. Actual officials have confirmed it.','I am going to be unbearable about this.','Somebody polish the trophy shelf. Optimistically.'],
retirement:['Professor {name} remembers when this was one room.','They say retirement is restful. Have they met students?','I learned that trick from {name}. Most of the safe ones, too.'],
item:['That {item} looks expensive to maintain.','The manufacturer insists the screaming is intentional.','Imagine who will carry that after us.'],
friend:['I saved you a seat. The one without teeth.','If we survive this, tea is on me.','I trust your aim. Mostly.','We make a reasonably survivable team.'],
rival:['Your technique is fascinating. Not correct, but fascinating.','The record board is over there. Look carefully.','I am not competitive. I am observably better.']};
export const ACHIEVEMENTS=[
['founders','The First Five','Recruit five founding wizards','recruited',5,3],['firstfloor','The First Stair','Clear your first floor','depth',1,2],['ten','Below the Foundation','Clear floor 10','depth',10,8],['fifty','Building on a Problem','Clear floor 50','depth',50,20],['hundred','Deeply Unwise','Clear floor 100','depth',100,40],['twohundred','The Long Descent','Clear floor 200','depth',200,70],['boss1','Tenure Revoked','Defeat a boss','bossKills',1,5],['boss50','Performance Review','Defeat 50 bosses','bossKills',50,15],['damage','A Firmly Worded Spell','Deal 100,000 damage','damage',100000,10],['heals','Bedside Manner','Heal 10,000 HP','healing',10000,8],['summons','Staff Shortage Solved','Create 500 summons','summons',500,10],['runes','Industrial Calligraphy','Produce 1,000 runes','runes',1000,8],['seals','Sealed with Concern','Produce 100 seals','seals',100,8],['gold','Healthy Endowment','Earn 100,000 gold','gold',100000,15],['wins','A Sporting Chance','Win a Rift match','wins',1,3],['wins100','Institutional Spite','Win 100 Rift matches','wins',100,15],['champ','Silverware','Win a league championship','championships',1,12],['champ10','A Dynasty','Win ten championships','championships',10,35],['century','The Institution Remains','Reach year 100','years',100,50],['fivehundred','Older Than the Rules','Reach year 500','years',500,100],['recovery','No Staff Left Behind','Recover a lost cache','recoveries',1,5],['legend','Living Legend','Find a Legendary item','legendary',1,12],['mythic','Footnote in Reality','Find a Mythic item','mythic',1,25],['outlier','Statistical Objection','Find an Anomalous roll','anomalous',1,15],['faculty','Those Who Teach','Appoint retired faculty','faculty',1,5],['hall','Remember This Name','Induct a Hall of Fame member','hall',1,8],['incidents','Insurance Premium','Survive 25 incidents','incidents',25,5],['livestock','Not a Sheep','Be mistaken for livestock','livestock',1,3],['loot','The Hoard','Discover 250 items','items',250,12],['training','Practice Makes Paperwork','Train for 100 hours','training',100,6],['relationships','A Place to Belong','Form ten close relationships','friendships',10,8],['research','Peer Reviewed','Complete 100 research units','research',100,15]];
