import {markWielder} from './provenance.js';
import {rnd,year,attributes,gainXP,news,uid,item,archive} from './model.js';
import {skillXP,practiceMagic,initializeWizard,backpackCount,backpackCapacity} from './progression.js';
import {emitCombatEvent} from './combat-events.js';
import {FAMILIES} from './data.js';
export const REGIONS=[
{name:'Forest Outskirts',level:1,depth:0,creature:'Briar Hare',drops:['Raw Meat','Soft Pelt','Wild Herbs']},
{name:'Whispering Woods',level:5,depth:2,creature:'Dire Wolf',drops:['Raw Meat','Wolf Pelt','Monster Bones','Dire Fang']},
{name:'Fungal Hollow',level:12,depth:5,creature:'Sporeling',drops:['Fungal Spores','Wild Herbs','Mana Crystal']},
{name:'Moonlit Grove',level:22,depth:10,creature:'Moon Wisp',drops:['Wisp Essence','Moonbloom','Mana Crystal']},
{name:'Goblin Warrens',level:35,depth:20,creature:'Goblin Raider',drops:['Goblin Scrap','Monster Bones','Raw Meat']},
{name:'Ancient Thicket',level:50,depth:30,creature:'Elder Treant',drops:['Treant Bark','Ancient Sap','Wild Herbs']},
{name:'Wisp Marsh',level:70,depth:45,creature:'Marsh Wisp',drops:['Wisp Essence','Fungal Spores','Mana Crystal']},
{name:'Spiderwood',level:95,depth:60,creature:'Silk Widow',drops:['Spider Silk','Monster Bones','Venom Sac']},
{name:'The Deep Wilds',level:130,depth:90,creature:'Wild Guardian',drops:['Ancient Sap','Mana Crystal','Treant Bark']}];
const PERIOD=90000,STRIKE=6000;
function battles(s){return s.forestBattles||(s.forestBattles={});}
export function assignForest(s,w,index){if(w.status!=='Active'||s.expedition?.ids.includes(w.id)||w.forestRescue)throw Error('This wizard is unavailable.');const r=REGIONS[index];if(!r||s.depth<r.depth)throw Error('Explore more dungeon floors to find this region.');initializeWizard(w);delete battles(s)[w.id];w.forestRegion=index;w.job='forest';w.forestProgress=0;w.forestLast='Hunting';}
export function returnForest(s,w,reason='Returned'){delete battles(s)[w.id];w.job='rest';w.forestProgress=0;w.forestLast=reason;w.forestLastAt=s.time;w.forestRegion=null;if(reason==='Low health')s.reputation.Safety=Math.min(100,(s.reputation.Safety||0)+.05);if(reason!=='Returned')news(s,`${w.name} returned from the forest: ${reason}.`,'forest');}
export function payRescue(s,w){if(!w.forestRescue)throw Error('No rescue bill is due.');if(s.gold<w.forestRescue)throw Error(`Recovery requires ${w.forestRescue} gold.`);s.gold-=w.forestRescue;w.forestRescue=0;w.job='recovery';w.hp=Math.max(1,Math.round(attributes(s,w).hp*.25));news(s,`${w.name} was carted home and is recovering.`,'recovery');}
function startBattle(s,w,r){const a=attributes(s,w),danger=(r.level/(w.level*12+10))*(w.forestRules.risk==='Cautious'?.7:w.forestRules.risk==='Aggressive'?1.35:1),hp=Math.max(9,Math.round(a.power*(4+danger*3)));const battle={id:uid(s,'forest'),kind:'forest',region:w.forestRegion,floor:w.forestRegion+1,state:'fighting',time:0,heroes:[{id:w.id,name:w.name,side:'hero',position:w.position||'Middle',hp:w.hp??a.hp,maxHP:a.hp,mana:w.mana??a.mana,maxMana:a.mana,status:{},barrier:0}],enemies:[{id:'creature',name:r.creature,side:'enemy',hp,maxHP:hp,power:Math.max(2,Math.round(a.hp*(.025+danger*.05))),status:{},barrier:0}],summons:[],log:[],fx:[],boss:false};battles(s)[w.id]=battle;return battle;}
function event(c,kind,from,to,family,ability,amount,old){emitCombatEvent(c,{kind,sourceId:from.id,targetId:to.id,family,ability,amount,hpBefore:old,hpAfter:to.hp,critical:false,absorbed:0});c.log.push({t:Math.round(c.time),text:`${from.name} ${ability}: ${Math.round(amount)}.`});c.log=c.log.slice(-12);}
function rescued(s,w,r,c){const cost=Math.round(24+r.level*1.8+w.level*1.2);w.hp=0;w.forestRescue=cost;w.job='rescued';w.forestLast=`Carted out · ${cost} gold due`;w.forestLastAt=s.time;c.state='defeat';news(s,`${w.name} was incapacitated in ${r.name}. Recovery costs ${cost} gold.`,'forest');s.reputation.Safety=Math.max(-100,(s.reputation.Safety||0)-.25);}
function reward(s,w,r,c){c.state='victory';w.stats.forestKills=(w.stats.forestKills||0)+1;markWielder(s,w,'forestKills');gainXP(s,w,Math.max(2,Math.round(r.level*.7)));const rare=new Set(['Dire Fang','Moonbloom','Ancient Sap','Venom Sac']),common=r.drops.filter(x=>!rare.has(x)),rareOptions=r.drops.filter(x=>rare.has(x)),drop=rareOptions.length&&rnd(s)<.045?rareOptions[Math.floor(rnd(s)*rareOptions.length)]:common[Math.floor(rnd(s)*common.length)],skill=drop.includes('Herb')||drop==='Moonbloom'?'Herbalism':drop.includes('Crystal')?'Mining':drop.includes('Bark')?'Woodcutting':'Foraging';skillXP(s,w,skill,3+r.level*.25);if(w.forestRules.loot!=='Valuable items'||rare.has(drop))w.backpack[drop]=(w.backpack[drop]||0)+1;
 if(w.stats.forestKills%100===0)news(s,`${w.name} has defeated ${w.stats.forestKills} forest creatures.`,'forest');
 // Exceptional encounters can reveal equipment, but the normal yield is materials.
 if(r.depth>=10&&rnd(s)<.0015){const it=item(s,Math.max(1,r.depth),false,w);w.legacy.unshift(`Year ${year(s)}: Discovered ${it.name} in ${r.name}.`);w.legacy=w.legacy.slice(0,16);}
 if(backpackCount(w)>=backpackCapacity(w)){if(w.forestRules.full==='Drop lowest'){const key=Object.keys(w.backpack).find(k=>w.backpack[k]>0);if(key)w.backpack[key]--;}else returnForest(s,w,'Inventory full');}
}
function strike(s,w,r,c){if(c.state!=='fighting')return;const h=c.heroes[0],e=c.enemies[0],a=attributes(s,w),focus=s.items.find(i=>i.id===w.equipment?.focus),f=focus&&FAMILIES.find(x=>x.id===focus.family),rkey=focus?.family+(focus?.tier>1?focus.tier:'');let family='arcane',ability='Magic Missile',power=a.power*(.72+rnd(s)*.5);if(f&&h.mana>=6&&(s.runes[rkey]||0)>=focus.charges){family=f.id;ability=f.spell;s.runes[rkey]-=focus.charges;h.mana-=6;power*=1.2+focus.tier*.12;practiceMagic(s,w,f.id,1.8);}else practiceMagic(s,w,'arcane',.4);
 let old=e.hp;e.hp=Math.max(0,e.hp-Math.max(1,Math.round(power)));event(c,'projectile',h,e,family,ability,old-e.hp,old);if(e.hp===0){w.hp=h.hp;w.mana=h.mana;reward(s,w,r,c);return;}
 const damage=Math.max(1,Math.round(e.power*(.7+rnd(s)*.6)-a.defense*.12));old=h.hp;h.hp=Math.max(0,h.hp-damage);event(c,'projectile',e,h,'hostile','Strike',old-h.hp,old);w.hp=h.hp;w.mana=h.mana;if(h.hp===0){rescued(s,w,r,c);return;}
 const threshold=Math.max(5,Math.min(90,Number(w.forestRules.retreat)||30));if(h.hp/h.maxHP*100<=threshold&&w.forestRules.risk!=='Aggressive'){c.state='retreat';returnForest(s,w,'Low health');return;}
 if(s.potions>0&&w.forestRules.potions!=='Conservative'&&h.hp/h.maxHP<(w.forestRules.potions==='Liberal'?.5:.25)){s.potions--;old=h.hp;h.hp=Math.min(h.maxHP,h.hp+h.maxHP*.45);w.hp=h.hp;event(c,'heal',h,h,'restoration','Potion',h.hp-old,old);}
}
export function forestTick(s,dt){for(const w of s.wizards){if(w.status!=='Active'||w.job!=='forest'||s.expedition?.ids.includes(w.id))continue;initializeWizard(w);const r=REGIONS[w.forestRegion];if(!r){returnForest(s,w);continue;}let left=dt,iterations=0;while(left>0&&w.job==='forest'&&iterations++<1500){let progress=w.forestProgress||0,c=battles(s)[w.id];if(!c&&progress===0){const threshold=Math.max(5,Math.min(90,Number(w.forestRules.retreat)||30));if((w.hp??attributes(s,w).hp)/attributes(s,w).hp*100<=threshold){returnForest(s,w,'Low health');break;}c=startBattle(s,w,r);}const next=c?.state==='fighting'?Math.min(PERIOD,Math.floor(progress/STRIKE+1)*STRIKE):PERIOD;const step=Math.min(left,Math.max(1,next-progress));progress+=step;left-=step;w.forestProgress=progress;if(c?.state==='fighting'&&progress>=next){c.time=progress/1000;strike(s,w,r,c);}if(progress>=PERIOD){w.forestProgress=0;delete battles(s)[w.id];if(c?.state==='fighting'){c.state='retreat';returnForest(s,w,'Could not finish the encounter');}else if(w.job==='forest')w.forestLast=`${r.creature} defeated · ${w.stats.forestKills||0} victories`;}}
 }}
