import {highlight,rollRarity,rarityOdds} from './rewards.js';
import {ensureJerseys} from './jerseys.js';
import {VERSION,DAY,FIRST,LAST,TRAITS,FAMILIES,RARITIES,AFFIXES,ROOMS,STATS,BOSSES,ACHIEVEMENTS} from './data.js';
export const clone=x=>JSON.parse(JSON.stringify(x));
export function rnd(s){let t=s.rng+=0x6D2B79F5;s.rng>>>=0;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;}
export const pick=(s,a)=>a[Math.floor(rnd(s)*a.length)];
export const integer=(s,a,b)=>a+Math.floor(rnd(s)*(b-a+1));
export const uid=(s,p)=>`${p}_${s.id}_${(++s.serial).toString(36).padStart(10,'0')}`;
export const year=s=>Math.floor(s.time/DAY)+1;
export const age=(s,w)=>Math.floor(w.startAge+(s.time-w.joined)/DAY);
export const active=s=>s.wizards.filter(w=>w.status==='Active');
export const living=s=>s.wizards.filter(w=>w.status!=='Deceased');
export const capacity=s=>5+Math.max(0,s.rooms.dorm-1)*5;
export function archive(s,type,id,data){s.pending[`${type}/${id}`]={type,id,data:clone(data)};}
export function news(s,text,kind='academy'){const e={id:uid(s,'n'),year:year(s),time:s.time,text,kind};s.feed.unshift(e);s.feed=s.feed.slice(0,70);archive(s,'timeline',e.id,e);return e;}
export function stat(s,w,k,n=1){if(!Number.isFinite(n))return; if(w){w.stats[k]=(w.stats[k]||0)+n;w.yearStats=w.yearStats||{};w.yearStats[k]=(w.yearStats[k]||0)+n;}s.stats[k]=(s.stats[k]||0)+n;}
export function record(s,w,k){const v=w.stats[k]||0;if(v<=0)return;const rows=s.records[k]||(s.records[k]=[]),prev=rows[0];const i=rows.findIndex(r=>r.id===w.id);if(i>=0)rows.splice(i,1);rows.push({id:w.id,name:w.name,value:v,status:w.status,hof:!!w.hof});rows.sort((a,b)=>b.value-a.value);rows.length=Math.min(25,rows.length);if(prev&&prev.id!==rows[0].id&&rows[0].id===w.id&&v>prev.value&&['depth','goals','bossKills','largestHit'].includes(k))news(s,`${w.name} breaks the ${STATS[k].toLowerCase()} record: ${Math.round(v).toLocaleString()}.`,'record');}
export function refreshRecords(s,w){for(const k of Object.keys(STATS))record(s,w,k);archive(s,'wizards',w.id,{...w,lastYear:year(s),age:w.departure?.age||age(s,w)});if(w.hof)archive(s,'honors',w.id,{...w,lastYear:year(s),age:w.departure?.age||age(s,w)});}
export function wizard(s,ai=false,tier=0){const startAge=integer(s,17,23),potential=integer(s,35,95);return {id:uid(s,'w'),name:pick(s,FIRST)+' '+pick(s,LAST),startAge,joined:s.time,status:'Active',level:1,xp:0,sportLevel:1,sportXP:0,potential,trait:integer(s,0,TRAITS.length-1),color:pick(s,['#c38971','#a9abc9','#a5bc83','#ceb27d','#a38ab9','#79aaa1','#b87b8e']),skin:pick(s,['#e2b48e','#bb825d','#8b5c46','#f1ceb3','#c99375']),hair:integer(s,0,4),hpBase:integer(s,78,100),manaBase:integer(s,36,55),powerBase:integer(s,9,13),sport:Object.fromEntries(['Speed','Control','Power','Defense','Awareness'].map(k=>[k,integer(s,22,42)+tier*10+(ai?integer(s,0,8):0)])),job:'rest',position:'Middle',directive:'Balanced',equipment:{focus:null,robe:null,charm:null},hp:null,mana:null,injury:null,retireAt:integer(s,57,65),deathAt:integer(s,80,94),stats:{},yearStats:{},relationships:{},notes:[],progress:0,hof:false};}
export function applicants(s){s.applicants=s.applicants.filter(w=>w.expires>s.time);const n=Math.min(14,5+Math.floor(Math.sqrt(s.prestige)/2));for(let i=0;i<n;i++){const w=wizard(s);const boost=Math.min(25,Math.log2(s.prestige+1)*2);w.hpBase+=Math.round(boost);w.potential=Math.min(100,w.potential+Math.floor(boost));w.expires=s.time+3*DAY;s.applicants.push(w);}s.applicants=s.applicants.slice(-45);news(s,`${n} applicants arrive carrying hope, luggage, and no liability coverage.`,'applicants');}
export function recruit(s,id){if(active(s).length>=capacity(s))throw Error('Build more dormitory beds first.');const i=s.applicants.findIndex(w=>w.id===id);if(i<0)throw Error('That applicant has left.');const w=s.applicants.splice(i,1)[0];w.joined=s.time;delete w.expires;s.wizards.push(w);ensureJerseys(s);w.founder=s.stats.recruited<5;stat(s,w,'recruited');w.hp=attributes(s,w).hp;w.mana=attributes(s,w).mana;news(s,`${w.name} joins ${s.name}${w.founder?' as a founding wizard':''}.`);archive(s,'wizards',w.id,w);checkAchievements(s);return w;}
export function emergencyRecruit(s){if(!s.intro)throw Error('Open the academy first.');const count=Math.max(0,Math.min(5,capacity(s))-active(s).length);if(!count)throw Error('Emergency admissions are available only below five active wizards.');const newcomers=[];for(let i=0;i<count;i++){const w=wizard(s);w.emergency=true;w.hpBase=integer(s,78,84);w.manaBase=integer(s,36,40);w.powerBase=integer(s,9,10);w.potential=integer(s,35,45);for(const key of Object.keys(w.sport))w.sport[key]=integer(s,22,28);w.notes.push('Joined through emergency admissions. No recommendation letters. Considerable determination.');s.applicants.push(w);newcomers.push(recruit(s,w.id));}const living=active(s),used=new Set();s.lineup=Array.from({length:5},(_,i)=>{const id=s.lineup[i];if(id&&living.some(w=>w.id===id)&&!used.has(id)){used.add(id);return id;}return null;});const candidates=[...newcomers,...living].filter(w=>!w.injury&&!s.expedition?.ids.includes(w.id));for(let i=0;i<5;i++)if(!s.lineup[i]){const w=candidates.find(w=>!used.has(w.id));if(w){s.lineup[i]=w.id;used.add(w.id);}}s.bench=s.bench.map(id=>used.has(id)?null:id);news(s,`${newcomers.length} emergency recruits restore the active roster to five. The admissions desk has waived its usual requirement for recommendations.`,'applicants');return newcomers;}
export function makeGame(name,now=Date.now(),seed){const s={schema:1,version:VERSION,id:Math.random().toString(36).slice(2,10),rng:seed??Math.floor(Math.random()*4294967295),serial:0,name:name.trim().slice(0,48)||'The Wayward Academy',time:0,lastWall:now,revision:0,gold:650,prestige:0,blanks:20,ingredients:8,seals:1,potions:5,runes:Object.fromEntries(FAMILIES.map(f=>[f.id,0])),rooms:Object.fromEntries(ROOMS.map(r=>[r.id,0])),faculty:{},wizards:[],applicants:[],items:[],lost:[],depth:0,party:[],expedition:null,combat:null,farmFloor:1,bossFloor:10,feed:[],chat:[],records:{},itemRecords:{},stats:{recruited:0},achievements:[],pending:{},events:[],nextEvent:DAY*.45,nextChat:30000,chain:0,chainDue:0,lineup:[],bench:[],tactics:{tempo:'Balanced',focus:'Balanced',passing:'Balanced'},settings:{motion:true,sound:false},intro:0,league:null};news(s,`${s.name} is founded. The roof is provisional. The ambition is not.`);return s;}
export function openFoundation(s){if(s.intro)return;for(const id of ['desk','dorm','gate','storage','archives'])s.rooms[id]=1;s.intro=1;applicants(s);news(s,'The doors open. Five beds, one dungeon, and a worrying amount of paperwork.');}
export function attributes(s,w){const items=Object.values(w.equipment).map(id=>s.items.find(x=>x.id===id)).filter(Boolean),trait=TRAITS[w.trait][2],v={hp:w.hpBase+(w.level-1)*9,mana:w.manaBase+(w.level-1)*4,power:w.powerBase+(w.level-1)*1.1,defense:2+(w.level-1)*.25,crit:.06,items,affixes:items.flatMap(i=>i.affixes),families:items.map(i=>i.family)};for(const i of items){v.hp+=i.hp;v.mana+=i.mana;v.power+=i.power;v.defense+=i.defense;}if(trait==='hp')v.hp*=1.12;if(trait==='mana')v.mana*=1.15;if(trait==='defense')v.defense*=1.12;if(trait==='reckless'){v.power*=1.12;v.defense*=.92;}if(v.affixes.includes('guardian'))v.defense*=1.15;if(v.affixes.includes('critical'))v.crit+=.08;if(w.injury){v.power*=.8;v.defense*=.9;}for(const k of ['hp','mana','power','defense'])v[k]=Math.round(v[k]);return v;}
export function gainXP(s,w,n,sport=false){const key=sport?'sportXP':'xp',level=sport?'sportLevel':'level';w[key]+=n;let count=0;while(w[key]>=100*Math.pow(w[level],1.3)){w[key]-=100*Math.pow(w[level],1.3);w[level]++;count++;}if(count&&!sport){w.hp=Math.min(attributes(s,w).hp,(w.hp||0)+9*count);w.mana=Math.min(attributes(s,w).mana,(w.mana||0)+4*count);}if(count)highlight(s,{kind:'level',wizard:w.id,name:w.name,sport,from:w[level]-count,to:w[level]});return count;}
// A lognormal body is approximately bell-shaped near its mode, with an exponentially unlikely
// positive tail. There is no gameplay cap or max-roll constant. Finite IEEE-754 arithmetic
// and the PRNG have numerical limits; invalid machine values are resampled, never clamped.
export function roll(s){let x;do{const u=1-rnd(s),v=rnd(s);const z=Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);x=Math.exp(.24*z-.0288);}while(!Number.isFinite(x)||x<=0);return x;}
export const quality=x=>x<.78?'Poor':x<1.15?'Typical':x<1.4?'Fine':x<1.75?'Exceptional':x<2.15?'Extraordinary':'Anomalous';
export function item(s,floor=1,boss=false,owner=null){const rarity=rollRarity(rnd(s),floor,boss);const b=BOSSES[(Math.floor(floor/10)-1+10000)%10],sig=boss?pick(s,b.drops):null,slot=sig?.slot||pick(s,['focus','robe','charm']),family=sig?.family||pick(s,FAMILIES).id,base=(3+floor*1.25)*[1,1.18,1.48,1.9,2.6,3.7][rarity],q=roll(s),power=Math.round(base*q*(slot==='focus'?1:slot==='robe'?.25:.55)*10)/10;const available=AFFIXES.filter(a=>a.min<=rarity).slice(),affixes=[];for(let j=0;j<Math.min(5,rarity);j++){const idx=integer(s,0,available.length-1);affixes.push(available.splice(idx,1)[0].id);}const f=FAMILIES.find(f=>f.id===family);const it={id:uid(s,'i'),name:sig?.name||`${pick(s,['Quiet','Wayward','Unsanctioned','Patient','Whispering','Hollow','Venerable','Crooked','Lucent','Borrowed'])} ${f.name} ${slot==='focus'?pick(s,['Staff','Wand','Rod','Scepter']):slot==='robe'?pick(s,['Mantle','Vestments','Coat','Robes']):pick(s,['Signet','Locket','Brooch','Charm'])}`,slot,family,rarity,floor,power,hp:Math.round(base*roll(s)*(slot==='robe'?3:.45)),mana:Math.round(base*roll(s)*.75),defense:Math.round(base*roll(s)*(slot==='robe'?.45:.08)),roll:q,quality:quality(q),affixes,charges:rarity>=3?2:1,tier:floor>=60?3:floor>=25?2:1,locked:false,owner:null,owners:[],found:{year:year(s),floor,boss:boss?b.name:null,wizard:owner?.name||'Academy patrol'},value:Math.round(base*(rarity+1)*8)};s.items.push(it);shelveOverflow(s);if(owner)stat(s,owner,'items');else stat(s,null,'items');stat(s,owner,'lootValue',it.value);if(rarity===4)stat(s,null,'legendary');if(rarity===5)stat(s,null,'mythic');if(it.quality==='Anomalous')stat(s,null,'anomalous');for(const k of ['power','hp','mana','defense']){const key=`${family}_${k}`,prev=s.itemRecords[key];if(!prev||it[k]>prev.value)s.itemRecords[key]={id:it.id,name:it.name,value:it[k],year:year(s),quality:it.quality};}archive(s,'items',it.id,it);highlight(s,{kind:'loot',item:clone(it),odds:rarityOdds(floor,boss)[rarity]});if(rarity>=3||q>=1.75)news(s,`${it.quality} ${RARITIES[rarity]} discovery: ${it.name}, found on floor ${floor}.`,'loot');return it;}
export function equip(s,w,id,slot){if(w.status!=='Active'||s.expedition?.ids.includes(w.id))throw Error('Equipment can only change at the academy.');const it=s.items.find(i=>i.id===id);if(id&&!it)throw Error('Item not found.');if(it?.owner&&it.owner!==w.id)throw Error('Unequip that item from its current owner first.');slot=it?.slot||slot;const old=s.items.find(i=>i.id===w.equipment[slot]);if(old){old.owner=null;archive(s,'items',old.id,old);}w.equipment[slot]=it?.id||null;if(it){it.owner=w.id;if(!it.owners.some(x=>x.id===w.id))it.owners.push({id:w.id,name:w.name,year:year(s)});archive(s,'items',it.id,it);}const a=attributes(s,w);w.hp=Math.min(w.hp,a.hp);w.mana=Math.min(w.mana,a.mana);}
export function bonus(s,room){const w=s.wizards.find(w=>w.id===s.faculty[room]&&w.status==='Faculty');if(!w)return 1;const st=w.stats;return 1+Math.min(.75,room==='rift'?(w.sportLevel*.01+(st.championships||0)*.025):room==='runes'?.08+Math.log2(1+(st.runes||0))*.018:room==='infirmary'?.08+Math.log2(1+(st.healing||0))*.014:.08+w.level*.007+(st.bossKills||0)*.002);}
export function retire(s,w){if(w.status!=='Active')return;w.status='Retired';w.job='rest';s.party=s.party.filter(id=>id!==w.id);s.lineup=s.lineup.map(id=>id===w.id?null:id);for(const slot of Object.keys(w.equipment)){const it=s.items.find(i=>i.id===w.equipment[slot]);if(it){it.owner=null;archive(s,'items',it.id,it);}w.equipment[slot]=null;}news(s,`${w.name} retires at ${age(s,w)}. Their next chapter may be teaching.`,'retirement');refreshRecords(s,w);}
export function die(s,w,cause){if(w.status==='Deceased')return;w.status='Deceased';w.departure={year:year(s),age:w.departure?.age||age(s,w),cause};w.job='rest';for(const [r,id] of Object.entries(s.faculty))if(id===w.id)delete s.faculty[r];s.party=s.party.filter(id=>id!==w.id);s.lineup=s.lineup.map(id=>id===w.id?null:id);s.bench=s.bench.filter(id=>id!==w.id);news(s,`${w.name} ${cause==='old age'?`passed away peacefully at age ${age(s,w)}`:`died on ${cause}`}. Their record remains.`,'death');for(const x of active(s)){stat(s,x,'witnessed');if(x.relationships[w.id])x.notes=[`Remembered ${w.name}, lost in year ${year(s)}.`,...x.notes].slice(0,12);}refreshRecords(s,w);}
export function checkAchievements(s){s.stats.depth=s.depth;s.stats.years=year(s);for(const [id,name,desc,key,target,p] of ACHIEVEMENTS){if(!s.achievements.includes(id)&&(s.stats[key]||0)>=target){s.achievements.push(id);s.prestige+=p;news(s,`Achievement: ${name}. ${desc}. +${p} Prestige.`,'achievement');}}}
export function upgrade(s,id){const r=ROOMS.find(r=>r.id===id),lv=s.rooms[id];if(lv>=6)throw Error('This facility has reached its final architectural tier.');const cost=lv?Math.round((r.cost||140)*Math.pow(2.15,lv)):r.cost,req=r.prestige+lv*8;if(s.gold<cost||s.prestige<req)throw Error(`Requires ${cost} gold and ${req} Prestige.`);s.gold-=cost;s.rooms[id]++;news(s,`${r.name} ${lv?'expanded to tier '+(lv+1):'opened'}. The insurance forms have been updated.`);}
export function assign(s,w,job){if(w.status!=='Active'||s.expedition?.ids.includes(w.id))throw Error('That wizard is not available for reassignment.');const facility=['blank','seals',...FAMILIES.map(f=>f.id)].includes(job)?'runes':job==='recovery'?'infirmary':job==='athletics'?'rift':job==='garden'?'garden':job==='research'?'observatory':job==='training'?'training':null;if(facility&&!s.rooms[facility])throw Error('Open the appropriate facility first.');if(job==='farm'&&s.depth<1)throw Error('Clear a dungeon floor first.');if(job==='boss'&&s.depth<10)throw Error('Defeat a boss first.');w.job=job;w.progress=0;}

export function shelveOverflow(s){while(s.items.length>180){const it=s.items.find(i=>!i.owner&&!i.locked)||s.items.find(i=>!i.owner);if(!it)break;it.vault=true;archive(s,'items',it.id,it);s.items=s.items.filter(i=>i.id!==it.id);}}
