import {firebaseConfig} from './firebase-config.js';
import {clone} from './model.js';
export let account='local',authUser=null,cloudStatus='Local save',conflicted=false;
let db=null,fb=null,auth=null,cloud=null,flushing=false,releaseLock=null;
const SDK='https://www.gstatic.com/firebasejs/11.10.0/';
export function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('wizard-academy-v1',1);r.onupgradeneeded=()=>{r.result.createObjectStore('state');r.result.createObjectStore('history');};r.onsuccess=()=>{db=r.result;resolve(db);};r.onerror=()=>reject(r.error);});}
function request(r){return new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function connect(){if(fb)return fb;cloudStatus='Connecting';const [app,a,f]=await Promise.all([import(SDK+'firebase-app.js'),import(SDK+'firebase-auth.js'),import(SDK+'firebase-firestore.js')]);const application=app.initializeApp(firebaseConfig);auth=a.getAuth(application);cloud=f.getFirestore(application);fb={...a,...f};await a.setPersistence(auth,a.browserLocalPersistence);await new Promise(resolve=>{const off=a.onAuthStateChanged(auth,u=>{authUser=u;off();resolve();});});cloudStatus=authUser?'Connected':'Not signed in';return fb;}
export async function authenticate(email,password,signup=false){await connect();const result=await (signup?fb.createUserWithEmailAndPassword:fb.signInWithEmailAndPassword)(auth,email,password);authUser=result.user;return authUser;}
export async function resetPassword(email){await connect();await fb.sendPasswordResetEmail(auth,email);}
export async function signOut(){if(auth)await fb.signOut(auth);authUser=null;}
export async function lockAccount(id){if(releaseLock){releaseLock();releaseLock=null;}if(!navigator.locks)return true;return new Promise(resolve=>{navigator.locks.request('wizard-academy-'+id,{ifAvailable:true},lock=>{if(!lock){resolve(false);return;}resolve(true);return new Promise(release=>releaseLock=release);});});}
export async function load(id='local'){account=id;conflicted=false;const local=await request(db.transaction('state').objectStore('state').get(account));if(id==='local'){cloudStatus='Saved on this device';return local||null;}await connect();const ref=fb.doc(cloud,'users',id,'game','current');const snap=await fb.getDocFromServer(ref);if(!snap.exists()){cloudStatus='Cloud ready';return local||null;}const remote=JSON.parse(snap.data().payload);remote.revision=snap.data().revision;remote.pending=remote.pending||{};if(remote.schema>1)throw Error('This save was made by a newer game version. Update the game files first.');if(local&&local.id===remote.id&&local.revision===remote.revision){cloudStatus='Cloud connected';return local;}if(local&&local.id===remote.id&&local.revision!==remote.revision){await request(db.transaction('state','readwrite').objectStore('state').put(local,account+'-recovery'));cloudStatus='Cloud loaded · prior device save kept';}else cloudStatus='Cloud connected';return remote;}
export async function saveLocal(s){if(!db)await openDB();const snap=clone(s),saveAccount=account;return new Promise((resolve,reject)=>{const tx=db.transaction(['state','history'],'readwrite');tx.objectStore('state').put(snap,saveAccount);for(const a of Object.values(snap.pending)){tx.objectStore('history').put(a,[saveAccount,a.type,a.id]);}tx.oncomplete=()=>{if(saveAccount==='local'){for(const [key,v] of Object.entries(snap.pending))if(JSON.stringify(s.pending[key])===JSON.stringify(v))delete s.pending[key];cloudStatus='Saved on this device';}resolve();};tx.onerror=()=>reject(tx.error);});}
export async function saveCloud(s){if(account==='local'){await saveLocal(s);return;}if(flushing||conflicted)return;flushing=true;const saveAccount=account;try{await saveLocal(s);const snap=clone(s),entries=Object.entries(snap.pending).slice(0,350),remaining=Object.fromEntries(Object.entries(snap.pending).slice(350));snap.pending=remaining;const revision=s.revision||0,snapshotPayload=JSON.stringify({...snap,revision:revision+1});if(new Blob([snapshotPayload]).size>850000)throw Error('The active save is too large to sync safely. Export a backup before collecting more items.');cloudStatus='Saving to cloud';const ref=fb.doc(cloud,'users',saveAccount,'game','current');await fb.runTransaction(cloud,async tx=>{const doc=await tx.get(ref);const serverRevision=doc.exists()?doc.data().revision:0;if(serverRevision!==revision){const e=new Error('Another device has saved newer progress. Your local session is paused to prevent overwriting it. Export a backup, then reload the cloud save.');e.code='save-conflict';throw e;}for(const [,a] of entries){tx.set(fb.doc(cloud,'users',saveAccount,'history',`${a.type}_${a.id}`),{type:a.type,year:a.data.year||a.data.lastYear||0,payload:JSON.stringify(a.data)});}tx.set(ref,{schema:1,revision:revision+1,payload:snapshotPayload,updatedAt:fb.serverTimestamp()});});s.revision=revision+1;for(const [key,value] of entries)if(JSON.stringify(s.pending[key])===JSON.stringify(value))delete s.pending[key];cloudStatus='Cloud saved';await saveLocal(s);}catch(e){if(e.code==='save-conflict'){conflicted=true;cloudStatus='Device conflict — paused';}else cloudStatus='Local safe · cloud unavailable';throw e;}finally{flushing=false;}}
export async function getArchive(type,id){const pending=await request(db.transaction('history').objectStore('history').get([account,type,id]));if(account==='local')return pending?.data||null;const r=await fb.getDoc(fb.doc(cloud,'users',account,'history',`${type}_${id}`));if(r.exists())return JSON.parse(r.data().payload);return pending?.data||null;}
export async function listArchive(type,after='',limit=30){if(account!=='local'){const prefix=type+'_';const q=fb.query(fb.collection(cloud,'users',account,'history'),fb.orderBy(fb.documentId()),fb.startAfter(after?prefix+after:prefix),fb.endAt(prefix+'\uf8ff'),fb.limit(limit));const snap=await fb.getDocs(q);const rows=snap.docs.map(d=>({id:d.id.slice(prefix.length),data:JSON.parse(d.data().payload)}));return {rows,next:rows.length===limit?rows.at(-1).id:null};}return new Promise((resolve,reject)=>{const store=db.transaction('history').objectStore('history'),range=IDBKeyRange.bound([account,type,after],[account,type,'\uffff'],true,false),r=store.openCursor(range);const rows=[];r.onsuccess=()=>{const c=r.result;if(c&&rows.length<limit){rows.push({id:c.value.id,data:c.value.data});c.continue();}else resolve({rows,next:rows.length===limit?rows.at(-1).id:null});};r.onerror=()=>reject(r.error);});}
export async function exportBackup(s){await saveLocal(s);const archives=[];for(const type of ['wizards','athletes','items','timeline','matches','seasons','battles','events','conversations','honors']){let after='',result;do{result=await listArchive(type,after,200);archives.push(...result.rows.map(r=>({type,id:r.id,data:r.data})));after=result.next;}while(after);}const map=new Map(archives.map(x=>[x.type+'/'+x.id,x]));for(const [key,v] of Object.entries(s.pending))map.set(key,v);return JSON.stringify({format:'wizard-academy-backup',version:1,exported:new Date().toISOString(),state:s,archives:[...map.values()]},null,2);}
export async function importLocalBackup(file){const data=JSON.parse(await file.text());if(data.format!=='wizard-academy-backup'||data.version!==1||data.state?.schema!==1||!Array.isArray(data.state.wizards)||!Array.isArray(data.archives))throw Error('This is not a supported Wizard Academy backup.');if(account!=='local')throw Error('Sign out and choose local play before restoring a backup. Cloud academies are not overwritten by imports.');const s=data.state;s.revision=0;s.pending={};for(const a of data.archives){if(!['wizards','athletes','items','timeline','matches','seasons','battles','events','conversations','honors'].includes(a.type)||typeof a.id!=='string')throw Error('Invalid archive entry.');s.pending[a.type+'/'+a.id]=a;}await saveLocal(s);return s;}

export async function previousDeviceSave(){return request(db.transaction('state').objectStore('state').get(account+'-recovery'));}
