import assert from 'node:assert/strict';
import * as M from './model.js';
import {processTime} from './simulation.js';
import {initProduction,productionStatus} from './tasks.js';
import {applyWorkers} from './workers.js';
function game(){const s=M.makeGame('Shared Work',1000000,321);M.openFoundation(s);for(const w of s.applicants.slice(0,3))M.recruit(s,w.id);s.rooms.runes=1;s.blanks=100;for(const w of s.wizards)w.trait=0;return s;}
let count=0;function test(name,fn){fn();console.log('PASS',name);count++;}
test('Three equal workers produce one batch in one-third the solo time',()=>{const s=game();applyWorkers(s,'fire',1,[s.wizards[0].id]);const solo=productionStatus(s,'fire').cycle;applyWorkers(s,'fire',1,s.wizards.map(w=>w.id));const team=productionStatus(s,'fire');assert.ok(Math.abs(team.cycle*3-solo)<1e-9);processTime(s,s.lastWall+team.cycle*1000+1);assert.equal(s.runes.fire,12);assert.equal(s.blanks,99);assert.ok(Math.abs(s.wizards.reduce((n,w)=>n+(w.stats.runes||0),0)-1)<1e-9);});
test('Legacy progress migrates once and does not duplicate after reload',()=>{const s=game();for(const w of s.wizards){w.job='fire';w.progress=20;}initProduction(s);assert.equal(s.production['fire:1'],60);initProduction(s);assert.equal(s.production['fire:1'],60);const b=M.clone(s);initProduction(b);assert.equal(b.production['fire:1'],60);assert.ok(b.wizards.every(w=>w.progress===0));});
test('Reassignment preserves partial work and cannot apply an invalid tier partially',()=>{const s=game();applyWorkers(s,'fire',1,s.wizards.map(w=>w.id));processTime(s,s.lastWall+10000);const progress=s.production['fire:1'];applyWorkers(s,'fire',1,[]);assert.equal(s.production['fire:1'],progress);processTime(s,s.lastWall+5000);assert.equal(s.production['fire:1'],progress);applyWorkers(s,'fire',1,[s.wizards[0].id]);const before=JSON.stringify(s);assert.throws(()=>applyWorkers(s,'fire',3,s.wizards.map(w=>w.id)));assert.equal(JSON.stringify(s),before);});
test('Resource-starved teams bank only one ready batch and resume without a burst',()=>{const s=game();applyWorkers(s,'fire',1,s.wizards.map(w=>w.id));s.blanks=0;processTime(s,s.lastWall+600000);assert.equal(s.production['fire:1'],110);assert.equal(s.runes.fire||0,0);s.blanks=1;processTime(s,s.lastWall+1000);assert.equal(s.runes.fire,12);assert.equal(s.blanks,0);});
test('Split offline progression and serialization preserve shared production',()=>{const a=game();applyWorkers(a,'fire',1,a.wizards.map(w=>w.id));const b=M.clone(a);processTime(a,a.lastWall+120000);processTime(b,b.lastWall+60000);const c=M.clone(b);processTime(c,c.lastWall+60000);assert.equal(a.runes.fire,c.runes.fire);assert.equal(a.blanks,c.blanks);assert.equal(a.production['fire:1'],c.production['fire:1']);});
console.log(`${count} shared-production tests passed.`);
