import {FAMILIES,DAY} from './data.js';
import {news,year,archive,attributes,rnd} from './model.js';
export const SKILLS=['Destruction','Restoration','Warding','Summoning','Herbalism','Mining','Woodcutting','Foraging','Alchemy','Enchanting','Runecrafting','Smithing','Cooking','Research','Teaching'];
export const UNLOCKS={Herbalism:[[5,'Recognize rare herbs'],[20,'Harvest moonbloom'],[50,'Identify ancient flora'],[99,'Master herbalist']],Alchemy:[[5,'Field tonics'],[20,'Potent restorative draughts'],[50,'Grand elixirs'],[99,'Master alchemist']],Runecrafting:[[10,'Tier II inscriptions'],[25,'Tier III inscriptions'],[60,'Efficient rune circles'],[99,'Master runesmith']],Research:[[20,'Advanced surveys'],[60,'Original discoveries'],[99,'Master scholar']],Teaching:[[20,'Guided study'],[50,'Master instruction'],[99,'Legendary professor']]};
const COST=l=>Math.floor(70*Math.pow(l,1.55));
export function skillLevel(w,k){return w.skills?.[k]?.level||1;}
export function initializeWizard(w){if(!w.skills)w.skills={};if(!w.aptitudes)w.aptitudes={};if(!w.spellUse)w.spellUse={};if(!w.backpack)w.backpack={};if(!w.forestRules)w.forestRules={risk:'Balanced',potions:'Normal',retreat:30,loot:'Everything',full:'Return'};if(!w.ambition)w.ambition={kind:'Master a skill',target:'Destruction',goal:50,done:false};if(!w.legacy)w.legacy=[];return w;}
export function skillXP(s,w,k,amount){initializeWizard(w);if(!SKILLS.includes(k)||!Number.isFinite(amount)||amount<=0)return;const v=w.skills[k]||(w.skills[k]={level:1,xp:0});const multiplier=w.aptitudes[k]||1;v.xp+=amount*multiplier;let levels=0;while(v.xp>=COST(v.level)&&levels<200){v.xp-=COST(v.level++);levels++;}if(levels){const unlocks=(UNLOCKS[k]||[]).filter(([l])=>l<=v.level&&l>v.level-levels);for(const [l,label] of unlocks){w.legacy.unshift(`Year ${year(s)}: ${label} (${k} ${l}).`);news(s,`${w.name} unlocked ${label}.`,'skill');}if(v.level>=99&&v.level-levels<99)news(s,`${w.name} mastered ${k}. The academy remembers.`,'skill');w.legacy=w.legacy.slice(0,16);checkAmbition(s,w);}}
export function chooseAptitudes(s,w){initializeWizard(w);const a=SKILLS[Math.floor(rnd(s)*SKILLS.length)],b=SKILLS[(SKILLS.indexOf(a)+5+Math.floor(rnd(s)*9))%SKILLS.length];w.aptitudes[a]=1.5;w.aptitudes[b]=.8;w.ambition={kind:'Master a skill',target:a,goal:50,done:false};}
export function knownSpells(s,w){initializeWizard(w);return ['Magic Missile',...new Set(Object.values(w.equipment||{}).map(id=>s.items.find(i=>i.id===id)).filter(Boolean).map(i=>FAMILIES.find(f=>f.id===i.family)?.spell).filter(Boolean))];}
export function practiceMagic(s,w,family,amount=1){initializeWizard(w);const skill=family==='restoration'?'Restoration':family==='necromancy'?'Summoning':family==='barrier'?'Warding':'Destruction';skillXP(s,w,skill,amount);if(!family)return;const prior=w.spellUse[family]||0;w.spellUse[family]=prior+amount;if(prior<100&&w.spellUse[family]>=100){const name={fire:'Pyromancer',storm:'Stormcaller',frost:'Winterweaver',restoration:'Lifekeeper',necromancy:'Gravebinder',barrier:'Aegis Warden',nature:'Wildspeaker'}[family]||`${FAMILIES.find(f=>f.id===family)?.name||family} adept`;w.specialization=name;w.legacy.unshift(`Year ${year(s)}: Became a ${name}.`);news(s,`${w.name} has become a ${name}.`,'skill');}}
export function backpackCount(w){return Object.values(w.backpack||{}).reduce((n,v)=>n+v,0);}
export function backpackCapacity(w){return 18+Math.floor(skillLevel(w,'Foraging')/20)*2;}
export function transferBackpack(s,w){initializeWizard(w);for(const [k,v] of Object.entries(w.backpack)){if(v>0){s.materials[k]=(s.materials[k]||0)+v;delete w.backpack[k];}}}
export function setMaster(s,w,master){initializeWizard(w);if(master&&(!s.wizards.includes(master)||master.id===w.id||!['Active','Retired','Faculty'].includes(master.status)))throw Error('Choose an available, different master.');w.masterId=master?.id||null;if(master){w.legacy.unshift(`Year ${year(s)}: Apprenticed to ${master.name}.`);w.legacy=w.legacy.slice(0,16);news(s,`${master.name} takes ${w.name} as an apprentice.`,'relationship');}}
export function mentor(s,w,dt){const m=s.wizards.find(x=>x.id===w.masterId&&x.status!=='Deceased');if(!m||w.status!=='Active')return;if(w.job!==m.job&&w.job!=='training')return;const entries=Object.entries(m.skills||{}).filter(([k,v])=>v.level>skillLevel(w,k)+4);if(!entries.length)return;const [skill]=entries.sort((a,b)=>b[1].level-a[1].level)[0];skillXP(s,w,skill,dt/3600000*7);skillXP(s,m,'Teaching',dt/3600000*3);}
export function checkAmbition(s,w){const a=w.ambition;if(!a||a.done)return;if(a.kind==='Master a skill'&&skillLevel(w,a.target)>=a.goal||a.kind==='Reach a dungeon floor'&&(w.stats?.depth||0)>=a.goal||a.kind==='Win a Rift championship'&&(w.stats?.championships||0)>0){a.done=true;a.year=year(s);w.legacy.unshift(`Year ${a.year}: Fulfilled the ambition to ${a.kind.toLowerCase()}${a.target?' in '+a.target:''}.`);w.legacy=w.legacy.slice(0,16);news(s,`${w.name} fulfilled a lifelong ambition.`,'achievement');archive(s,'wizards',w.id,w);}}
