import assert from 'node:assert/strict';
import * as M from './model.js';
import * as L from './sports.js';
import {ensureJerseys,assignJersey} from './jerseys.js';
import {matchLineups,shownScore,stepBroadcast,PLAY_SECONDS,playerTarget,motePosition} from './rift-motion.js';
function game(){const s=M.makeGame('Number Nine',1000000,77);L.createLeague(s);M.openFoundation(s);for(const w of s.applicants.slice(0,5))M.recruit(s,w.id);s.rooms.rift=1;s.lineup=s.wizards.map(w=>w.id);return s;}
let passed=0;function test(name,fn){fn();console.log('PASS',name);passed++;}
test('Capacity reaches 30; uniforms migrate without RNG and reject collisions',()=>{const s=game();s.rooms.dorm=6;assert.equal(M.capacity(s),30);const rng=s.rng;delete s.wizards[0].jersey;ensureJerseys(s);assert.equal(s.rng,rng);assert.equal(new Set(s.wizards.map(w=>w.jersey)).size,5);assert.throws(()=>assignJersey(s,s.wizards[0],s.wizards[1].jersey));assert.throws(()=>assignJersey(s,s.wizards[0],2.5));assignJersey(s,s.wizards[0],0);assert.equal(s.wizards[0].jersey,0);});
test('Match snapshots retain uniforms after reassignment and reload',()=>{const s=game();assignJersey(s,s.wizards[0],99);const rival=s.league.schools.find(t=>t.id!=='player'&&t.league===0),m=L.simulateMatch(s,'player',rival.id);assert.equal(m.lineups[0][0].number,99);assignJersey(s,s.wizards[0],98);assert.equal(M.clone(m).lineups[0][0].number,99);assert.ok(m.plays.filter(p=>p.actor).every(p=>p.kind&&Number.isInteger(p.shooter)&&Number.isInteger(p.guard)));});
test('Broadcast scores resolve on impact and watching cannot alter the saved match',()=>{const m={plays:[{side:0,score:[1,0]},{side:1,score:[1,0]}]},before=JSON.stringify(m),w={index:0,elapsed:0,playing:true};assert.deepEqual(shownScore(m,w),[0,0]);for(let i=0;i<55;i++)stepBroadcast(w,m,.06);assert.deepEqual(shownScore(m,w),[1,0]);for(let i=0;i<100;i++)stepBroadcast(w,m,.06);assert.equal(w.complete,true);assert.equal(w.playing,false);assert.equal(JSON.stringify(m),before);const elapsed=w.elapsed;stepBroadcast(w,m,1000);assert.equal(w.elapsed,elapsed);});
test('Dot and mote geometry stays bounded, and old matches still load',()=>{for(let phase=0;phase<=1;phase+=.05){const actors=Array.from({length:10},(_,i)=>playerTarget(i<5?0:1,i%5,0,phase,phase*10));for(const p of actors)assert.ok(p.x>=9&&p.x<=91&&p.y>=15&&p.y<=85);for(const kind of ['goal','steal','block','foul']){const p=motePosition(actors,{side:0,shooter:1,guard:4},phase,kind);assert.ok(Number.isFinite(p.x)&&Number.isFinite(p.y));}}const legacy={a:'a',b:'b',players:[{id:'w',team:'a',name:'Old Wizard'}]};assert.equal(matchLineups(legacy)[0][0].number,1);});
test('Eliminated teams and completed seasons do not advertise a nonexistent final',()=>{const s=game();s.league.round=16;assert.equal(L.nextFixture(s).stage,'offseason');s.league.round=15;s.league.playoffs[0]={finalists:['other1','other2']};assert.equal(L.nextFixture(s).stage,'offseason');});
console.log(`${passed} Rift tests passed.`);
