import {sound} from './sound.js';
export const PLAY_SECONDS=3.6;
const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n));
export function matchLineups(m){return m.lineups||[m.a,m.b].map(team=>m.players.filter(p=>p.team===team).map((p,i)=>({id:p.id,name:p.name,number:p.number??i+1,position:p.position??i})));}
export function playKind(m,index){const p=m.plays[index];if(!p)return 'opening';if(m.forfeit)return 'forfeit';if(p.kind)return p.kind;const before=m.plays[index-1]?.score||[0,0];return p.score.some((n,i)=>n>before[i])?'goal':/steal/i.test(p.text)?'steal':/penalized/i.test(p.text)?'foul':'block';}
export function shownScore(m,watch){const resolved=watch.elapsed>=PLAY_SECONDS*.88||watch.complete;return (resolved?m.plays[watch.index]:m.plays[watch.index-1])?.score||[0,0];}
export function stepBroadcast(watch,m,dt){if(!watch.playing||!m.plays.length)return;watch.elapsed=(watch.elapsed||0)+clamp(dt,0,.06);if(watch.elapsed>=PLAY_SECONDS){if(watch.index<m.plays.length-1){watch.index++;watch.elapsed=0;}else{watch.elapsed=PLAY_SECONDS;watch.complete=true;watch.playing=false;}}}
export function playerTarget(side,pos,index,phase,time,reduced=false){const attack=mixAttack(side,index),xBase=[62,60,43,24,25][pos]||40,yBase=[28,72,50,28,72][pos]||50;const shift=attack?7:-5,x=side===0?xBase+shift:100-xBase-shift;return {x:clamp(x+(reduced?0:Math.sin(time*.7+pos*2+side)*2.5),9,91),y:clamp(yBase+(reduced?0:Math.sin(time*.9+pos*1.7+side)*4),15,85)};}
function mixAttack(side,index){return side===index;}
export function motePosition(actors,play,phase,kind){const side=play?.side??0,shooter=play?.shooter??0,guard=play?.guard??3,controller=actors[side*5+2]||{x:50,y:50},striker=actors[side*5+shooter]||controller,defender=actors[(1-side)*5+guard]||{x:50,y:50},goal={x:side===0?94:6,y:50};let from,to,t;if(phase<.38){from=controller;to=striker;t=phase/.38;}else{from=striker;to=kind==='goal'?goal:kind==='foul'?striker:defender;t=(phase-.38)/.5;}t=clamp(t);t=t*t*(3-2*t);return {x:from.x+(to.x-from.x)*t,y:from.y+(to.y-from.y)*t-Math.sin(t*Math.PI)*4};}
let running=false;
export function startRiftBroadcast(getState){if(running)return;running=true;let previous=0,currentId=null,actors=[],visualTime=0,lastWatch=null,lastPlay=-1,cues=new Set();
 function frame(now){requestAnimationFrame(frame);const dt=clamp((now-previous)/1000,0,.06);previous=now;const state=getState(),pitch=document.getElementById('rift-live-pitch');if(!state||!pitch||!pitch.isConnected||document.hidden)return;const {match:m,watch}=state;if(currentId!==m.id){currentId=m.id;actors=[];visualTime=0;}stepBroadcast(watch,m,dt);const reduced=m.forfeit||state.motion===false||window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(watch.playing)visualTime+=dt;if(lastWatch!==watch||watch.index<lastPlay){cues.clear();lastWatch=watch;}lastPlay=watch.index;const play=m.plays[watch.index],phase=clamp((watch.elapsed||0)/PLAY_SECONDS),kind=playKind(m,watch.index);if(watch.playing){for(const [stage,at,cue] of [['pass',.15,'rift-pass'],['finish',.88,kind==='goal'?'rift-goal':kind==='foul'||kind==='forfeit'?'rift-whistle':'rift-save']]){const key=watch.index+stage;if(phase>=at&&!cues.has(key)){cues.add(key);sound(cue);}}}
 for(let i=0;i<10;i++){const el=pitch.querySelector(`[data-rift-player="${i}"]`);if(!el)continue;const target=playerTarget(Math.floor(i/5),i%5,play?.side??0,phase,visualTime,reduced);if(!actors[i])actors[i]=target;if(watch.playing||reduced){const blend=reduced?1:Math.min(1,dt*2.5);actors[i]={x:actors[i].x+(target.x-actors[i].x)*blend,y:actors[i].y+(target.y-actors[i].y)*blend};}el.style.left=actors[i].x+'%';el.style.top=actors[i].y+'%';el.classList.toggle('has-mote',i===(play?.side??0)*5+(phase<.38?2:play?.shooter??0)&&phase<.5);}
 const mote=pitch.querySelector('.mote');if(mote){const p=motePosition(actors,play,phase,kind);mote.style.left=p.x+'%';mote.style.top=p.y+'%';mote.style.opacity=m.forfeit?'0':'1';}const event=pitch.querySelector('.rift-call');if(event){event.textContent=phase>=.88||watch.complete?({goal:'APERTURE!',block:'WARD SAVE',steal:'INTERCEPTED',foul:'FOUL',forfeit:'FORFEIT'}[kind]||''):'';}
 }
 requestAnimationFrame(frame);
}
