import {forestTick} from './forest.js';
import {skillXP,mentor,initializeWizard,checkAmbition} from './progression.js';
import {workRate,workDuration,initProduction,productionGroups} from './tasks.js';
import {DAY,HOUR,CAP,FAMILIES,TRAITS,EVENT_LIBRARY,CHAT} from './data.js';
import {rnd,pick,integer,uid,year,age,active,attributes,bonus,stat,gainXP,applicants,retire,die,refreshRecords,archive,news,item,checkAchievements,wizard} from './model.js';
import {playRound,endSeason} from './sports.js';
import {farm,recoverCache,bossFor} from './combat.js';
export function processTime(s,now=Date.now()){initProduction(s);s.materials||={};s.reputation||={Academic:0,Dungeon:0,Rift:0,Research:0,Safety:0};for(const w of [...s.wizards,...s.applicants])initializeWizard(w);const wall=Math.max(s.lastWall,now),raw=Math.max(0,wall-s.lastWall),elapsed=Math.min(CAP,raw),before={gold:s.gold,blanks:s.blanks,seals:s.seals,potions:s.potions,runes:Object.values(s.runes).reduce((a,b)=>a+b,0),levels:active(s).reduce((a,w)=>a+w.level,0),matches:s.stats.appearances||0,feed:s.feed[0]?.id},target=s.time+elapsed;while(s.time<target){const next=Math.min(target,(Math.floor(s.time/60000)+1)*60000),dt=next-s.time,oldYear=year(s);s.time=next;work(s,dt);forestTick(s,dt);if(s.time%60000===0){minute(s);if(s.league){while(s.league.round<16&&s.time>=(s.league.year-1)*DAY+(s.league.round+1)*DAY/17)playRound(s);if(year(s)>s.league.year)endSeason(s);}if(year(s)>oldYear)annual(s);}if(s.time>=s.nextChat){conversation(s);s.nextChat=s.time+integer(s,35000,65000);}if(s.time>=s.nextEvent&&s.intro){createEvent(s);s.nextEvent=s.time+DAY*(.55+rnd(s)*.25);}if(s.chainDue&&s.time>=s.chainDue){s.chainDue=0;s.events.push({id:uid(s,'event'),title:'The older academy',body:'Your sealed correspondence has led to a room beneath the oldest foundation. A name has been carefully erased.',choices:[{label:'Restore the forgotten name',cost:150,reward:'prestige',amount:18,result:'The first founder’s name is restored. The room grows quiet.'},{label:'Preserve the discovery',cost:0,reward:'ingredients',amount:25,result:'The archives gain a new chapter.'}],year:year(s)});}}
 s.lastWall=wall;checkAchievements(s);const result={elapsed,capped:raw>CAP,gold:s.gold-before.gold,blanks:s.blanks-before.blanks,seals:s.seals-before.seals,potions:s.potions-before.potions,runes:Object.values(s.runes).reduce((a,b)=>a+b,0)-before.runes,levels:active(s).reduce((a,w)=>a+w.level,0)-before.levels,events:s.feed.slice(0,15).filter(e=>e.time>=target-elapsed)};return result;}
function work(s,dt){for(const w of active(s)){if(s.expedition?.ids.includes(w.id)||w.job==='rescued')continue;mentor(s,w,dt);const a=attributes(s,w),trait=TRAITS[w.trait][2];const recover=w.job==='recovery'?3*bonus(s,'infirmary')*(1+s.rooms.infirmary*.2):w.job==='rest'?1.6:1;w.hp=Math.min(a.hp,(w.hp??a.hp)+a.hp*dt/900000*recover);w.mana=Math.min(a.mana,(w.mana??a.mana)+a.mana*dt/600000*recover);if(w.injury){if(w.job==='recovery')w.injury.until-=dt*(bonus(s,'infirmary')+(trait==='recovery'?.2:0));if(w.injury.until<=s.time){news(s,`${w.name} has recovered from ${w.injury.name}.`,'recovery');w.injury=null;}}const job=w.job;const mult=workRate(s,w);
 if(job==='training'){const amount=dt/HOUR;stat(s,w,'training',amount);gainXP(s,w,amount*160*mult*(trait==='training'?1.15:1));skillXP(s,w,'Warding',amount*18);}
 else if(job==='athletics')gainXP(s,w,dt/HOUR*75*mult,true);

 }produce(s,dt);}
function produce(s,dt){const groups=productionGroups(s,['blank','seals','garden','research','clerical',...FAMILIES.map(f=>f.id)]);for(const g of groups){if(!g.rate)continue;let progress=g.stored+dt/1000*g.rate;while(progress>=g.duration){const current=productionGroups(s,[g.job]).find(x=>x.tier===g.tier);if(current.blocked){progress=g.duration;break;}progress-=g.duration;let metric=null;
 if(g.job==='blank'){s.blanks++;metric='runes';}else if(g.job==='seals'){s.ingredients-=3;s.gold-=8;s.seals++;metric='seals';}else if(g.job==='garden'){s.gold-=6;s.potions++;}else if(g.job==='research'){s.blanks-=3;s.prestige+=.25;metric='research';}else if(g.job==='clerical'){s.gold+=2;metric='gold';}else{s.blanks--;const key=g.job+(g.tier>1?g.tier:'');s.runes[key]=(s.runes[key]||0)+12;metric='runes';}
 for(const w of g.workers){const keySkill=g.job==='garden'?'Alchemy':g.job==='research'?'Research':g.job==='seals'?'Enchanting':g.job==='clerical'?'Teaching':'Runecrafting';skillXP(s,w,keySkill,15);const share=workRate(s,w)/g.rate;if(metric)stat(s,w,metric,share*(g.job==='clerical'?2:1));if(FAMILIES.some(f=>f.id===g.job))gainXP(s,w,share);}
 }s.production[g.key]=progress;}}

function minute(s){s.applicants=s.applicants.filter(w=>w.expires>s.time);for(const cache of s.lost.slice())if(cache.ready&&cache.ready<=s.time)recoverCache(s,cache);if(s.time%300000===0){farm(s,'farm');farm(s,'boss');}for(const w of s.wizards.slice()){if(s.expedition?.ids.includes(w.id))continue;if(w.status!=='Deceased'&&age(s,w)>=w.deathAt)die(s,w,'old age');else if(w.status==='Active'&&age(s,w)>=w.retireAt)retire(s,w);}s.wizards=s.wizards.filter(w=>w.status!=='Deceased'||s.combat?.heroes.some(h=>h.id===w.id));}
function annual(s){applicants(s);for(const w of s.wizards){checkAmbition(s,w);refreshRecords(s,w);w.yearStats={};}news(s,`Year ${year(s)} begins. The academy remains.`,'year');}
export function conversation(s){const ws=s.wizards.filter(w=>w.status!=='Deceased'&&!s.expedition?.ids.includes(w.id));if(!ws.length)return;const a=pick(s,ws),b=ws.length>1?pick(s,ws.filter(w=>w.id!==a.id)):null;let category=a.injury?'injury':a.status==='Faculty'?'retirement':a.job==='training'?'training':['athletics'].includes(a.job)?'rift':a.job==='blank'||FAMILIES.some(f=>f.id===a.job)?'runes':'rest';const recent=s.feed.find(e=>['death','boss','loot','championship','retirement'].includes(e.kind));if(recent&&s.time-recent.time<HOUR&&rnd(s)<.4)category=recent.kind==='death'?'loss':recent.kind==='loot'?'item':recent.kind==='championship'?'win':recent.kind;let relation=null;if(b){const pair=a.relationships[b.id]||(a.relationships[b.id]={name:b.name,value:0,kind:'Acquaintance'});pair.value+=TRAITS[a.trait][2]==='social'?2:1;if(a.trait===b.trait)pair.value+=1;if((a.trait+b.trait)%7===0)pair.value-=3;const old=pair.kind;pair.kind=pair.value>=20?'Friend':pair.value<=-12?'Rival':a.status==='Faculty'?'Mentor':'Acquaintance';if(old!=='Friend'&&pair.kind==='Friend'){stat(s,null,'friendships');news(s,`${a.name} and ${b.name} have become close friends.`,'relationship');}if(['Friend','Rival'].includes(pair.kind)&&rnd(s)<.3)category=pair.kind.toLowerCase();relation=pair.kind;if(Object.keys(a.relationships).length>16){const key=Object.keys(a.relationships).find(k=>k!==b.id&&Math.abs(a.relationships[k].value)<10);if(key)delete a.relationships[key];}}
 const text=pick(s,CHAT[category]||CHAT.rest).replaceAll('{boss}',bossFor(Math.max(10,Math.floor(s.depth/10)*10)).name).replaceAll('{floor}',String(s.depth)).replaceAll('{name}',a.name).replaceAll('{item}',s.items.at(-1)?.name||'staff');const msg={id:uid(s,'chat'),a:a.id,name:a.name,to:b?.name||null,text,time:s.time,relation};s.chat.unshift(msg);s.chat=s.chat.slice(0,30);if((relation==='Friend'||relation==='Rival')&&s.time-(s.lastChatArchive||0)>=1200000){archive(s,'conversations',msg.id,msg);s.lastChatArchive=s.time;}}
export function createEvent(s){const x=pick(s,EVENT_LIBRARY),e={id:uid(s,'event'),title:x[0],body:x[1],year:year(s),choices:[{label:x[2],cost:x[3],reward:x[4],amount:x[5],result:x[6]},{label:x[7],cost:x[8],reward:x[9],amount:x[10],result:'The decision is entered into the academy ledger.'}]};if(s.events.length<6)s.events.push(e);else {news(s,`${e.title}: the office resolves the matter quietly. +15 gold.`,'event');s.gold+=15;}const w=pick(s,active(s));if(w){stat(s,w,'incidents');if(rnd(s)<.08){stat(s,w,'friendlyFire');news(s,`${w.name} accidentally ignited a teammate’s practice robe. The teammate was not in it.`,'event');}if(rnd(s)<.03){stat(s,w,'livestock');news(s,`${w.name} was mistaken for livestock by a visiting dragon. The misunderstanding was resolved.`,'event');}}}
export function resolveEvent(s,id,index){const n=s.events.findIndex(e=>e.id===id);if(n<0)return;const e=s.events[n],c=e.choices[index];if(!c)return;if(s.gold<c.cost)throw Error('The academy cannot afford that option.');s.gold-=c.cost;if(c.reward==='item')item(s,Math.max(1,s.depth),false,pick(s,active(s)));else if(c.reward==='applicant'){const w=wizard(s);w.expires=s.time+3*DAY;s.applicants.push(w);}else if(c.reward==='runes')s.runes.arcane+=c.amount;else if(c.reward==='chain'){s.chain++;s.chainDue=s.time+3*DAY;}else s[c.reward]=(s[c.reward]||0)+c.amount;news(s,`${e.title} — ${c.result}`,'event');archive(s,'events',e.id,{...e,choice:index,resolvedYear:year(s)});s.events.splice(n,1);checkAchievements(s);}
