import assert from 'node:assert/strict';
import {audioSettings,startAudio,sound,refreshAudio} from './sound.js';
const listeners={},scheduled=[],sources=[];let ctx;
const param=()=>({value:0,setValueAtTime(v){assert.ok(Number.isFinite(v));},linearRampToValueAtTime(v){assert.ok(Number.isFinite(v));},exponentialRampToValueAtTime(v){assert.ok(v>0);},setTargetAtTime(v){assert.ok(Number.isFinite(v));}});
const node=()=>({connect(){},disconnect(){},gain:param(),frequency:param(),pan:param(),threshold:param(),ratio:param()});
globalThis.document={hidden:false,addEventListener(k,f){listeners[k]=f;}};globalThis.setInterval=f=>{scheduled.push(f);};
globalThis.AudioContext=class {constructor(){ctx=this;this.state='suspended';this.currentTime=1;this.sampleRate=8000;this.destination=node();}createGain(){return node();}createDynamicsCompressor(){return node();}createOscillator(){const o={...node(),start(){},stop(at){if(at===undefined)this.stopped=true;}};sources.push(o);return o;}createStereoPanner(){return node();}createBuffer(_,n){return {getChannelData:()=>new Float32Array(n)};}createBufferSource(){return this.createOscillator();}createBiquadFilter(){return node();}resume(){this.state='running';return Promise.resolve();}suspend(){this.state='suspended';return Promise.resolve();}};
const s={settings:{audio:{master:2,effects:-1}}};assert.equal(audioSettings(s).master,1);assert.equal(audioSettings(s).effects,0);s.settings.audio={enabled:true};startAudio(()=>({s,route:null}));assert.equal(ctx,undefined,'No audio context before a gesture');listeners.pointerdown();assert.equal(ctx.state,'running');
for(const name of ['select','room','cast','impact','critical','heal','shield','summon','phase','death','victory','defeat','loot','rare','equip','production','level','upgrade','recruit','coins','rift-pass','rift-goal','rift-save','rift-whistle','notice']){ctx.currentTime+=2;sound(name,{family:'fire',room:'runes'});for(const o of sources.splice(0))o.onended?.();}
assert.equal(sources.length,0);s.settings.audio.enabled=false;refreshAudio();sound('cast');assert.equal(sources.length,0,'Mute suppresses new voices');s.settings.audio.enabled=true;refreshAudio();ctx.currentTime+=3;sound('cast');const n=sources.length;sound('cast');assert.equal(sources.length,n,'Rapid identical sounds are throttled');document.hidden=true;listeners.visibilitychange();assert.equal(ctx.state,'suspended');assert.ok(sources.every(o=>o.stopped),'Hidden page stops pending audio');document.hidden=false;listeners.visibilitychange();assert.equal(ctx.state,'suspended','Return waits for user gesture');listeners.pointerdown();assert.equal(ctx.state,'running');console.log('PASS Sound recipes, gesture unlock, clamped controls, mute, throttling, and hidden-page cleanup.');
