import {markWielder} from './provenance.js';
import {recordReputation} from './careers.js';
import {ensureJerseys} from './jerseys.js';
import {DAY,LEAGUES,SCHOOLS,FAMILIES,TRAITS} from './data.js';
import {rnd,pick,integer,wizard,year,age,active,attributes,stat,gainXP,archive,news,bonus,refreshRecords,clone} from './model.js';
export function createLeague(s){s.league={year:1,round:0,schools:[{id:'player',name:s.name,league:0,personality:'headmaster',quote:'The roof is provisional. The ambition is not.',titles:0,career:{wins:0,losses:0,pf:0,pa:0},roster:[]},...SCHOOLS.map(x=>({...x,titles:0,career:{wins:0,losses:0,pf:0,pa:0},roster:Array.from({length:7},()=>{const w=wizard(s,true,x.league);w.startAge=integer(s,18,49);w.sportLevel=integer(s,1,4+x.league*3);return w;})}))],tables:{},matches:[],playoffs:{},headToHead:{},lastMatch:null,seasonPlayers:{},records:{},streak:0};resetTables(s);}
function resetTables(s){s.league.tables=Object.fromEntries(s.league.schools.map(t=>[t.id,{id:t.id,name:t.name,league:t.league,w:0,l:0,pf:0,pa:0}]));}
export const standings=(s,l)=>Object.values(s.league.tables).filter(t=>t.league===l).sort((a,b)=>b.w-a.w||(b.pf-b.pa)-(a.pf-a.pa)||b.pf-a.pf||a.id.localeCompare(b.id));
export const playerSchool=s=>s.league.schools.find(t=>t.id==='player');
function pairs(ids,round){const a=ids.slice();for(let r=0;r<round%7;r++)a.splice(1,0,a.pop());return Array.from({length:4},(_,i)=>round<7?[a[i],a[7-i]]:[a[7-i],a[i]]);}
export function nextFixture(s){const l=s.league,round=l.round,league=playerSchool(s).league;if(round>=14){const qualified=standings(s,league).slice(0,4).some(t=>t.id==='player'),finalists=l.playoffs[league]?.finalists||[],eligible=round===14?qualified:round===15?finalists.includes('player'):false;if(!eligible)return {label:'Next season · opponent pending',at:l.year*DAY+DAY/17,stage:'offseason'};if(round===15){const opponent=l.schools.find(t=>t.id===finalists.find(id=>id!=='player'));return {label:opponent?.name||'Championship',at:(l.year-1)*DAY+DAY*16/17,stage:'Championship'};}const seeds=standings(s,league).slice(0,4),index=seeds.findIndex(t=>t.id==='player');return {label:seeds[3-index].name,at:(l.year-1)*DAY+DAY*15/17,stage:'Semifinal'};}const ids=l.schools.filter(t=>t.league===league).map(t=>t.id);const pair=pairs(ids,round).find(p=>p.includes('player'));return {label:l.schools.find(t=>t.id===pair.find(id=>id!=='player')).name,at:(l.year-1)*DAY+DAY*(round+1)/17,stage:'Regular season'};}

function athletes(s,team){if(team.id!=='player')return team.roster.filter(w=>w.status==='Active').sort((a,b)=>rating(s,b,2)-rating(s,a,2)).slice(0,5);if(!s.rooms.rift)return [null,null,null,null,null];const eligible=active(s).filter(w=>!w.injury&&!s.expedition?.ids.includes(w.id));const roster=s.lineup.slice(0,5).map(id=>eligible.find(w=>w.id===id)||null),used=new Set(roster.filter(Boolean).map(w=>w.id));const reserves=s.bench.map(id=>eligible.find(w=>w.id===id)).filter(w=>w&&!used.has(w.id));for(let i=0;i<5;i++)if(!roster[i]&&reserves.length){const w=reserves.shift();roster[i]=w;used.add(w.id);}return roster;}
export function rating(s,w,pos){if(!w)return 0;const keys=pos<2?['Speed','Power','Control']:pos===2?['Control','Awareness','Speed']:['Defense','Awareness','Power'];let val=keys.reduce((n,k)=>n+w.sport[k],0)/3+(w.sportLevel-1)*(1+w.potential/100);if(w.injury)val*=.75;const a=attributes(s,w);for(const it of a.items){const f=FAMILIES.find(f=>f.id===it.family);val+=keys.includes(f.sport)?Math.log2(2+it.power)*1.6:Math.log2(2+it.power)*.4;}const trait=TRAITS[w.trait][2];if(keys.some(k=>k.toLowerCase()===trait))val*=1.12;const ag=age(s,w);if(ag>40)val*=Math.max(.65,1-(ag-40)*.012);return Math.round(val);}
export function simulateMatch(s,aId,bId,stage='regular',league=0){ensureJerseys(s);const a=s.league.schools.find(t=>t.id===aId),b=s.league.schools.find(t=>t.id===bId),rosters=[athletes(s,a),athletes(s,b)],teams=[a,b];const playerSide=aId==='player'?0:bId==='player'?1:-1;const tac=teams.map(t=>t.id==='player'?s.tactics:{tempo:['Slow','Balanced','Fast'][Math.floor(rnd(s)*3)],focus:t.personality==='military'||t.personality==='reckless'?'Offensive':t.personality==='patient'?'Defensive':'Balanced',passing:t.personality==='analytical'?'Safe':'Balanced'});const ratings=rosters.map((r,j)=>r.map((w,i)=>rating(s,w,i)*(teams[j].id==='player'?bonus(s,'rift'):1)));
 const m={id:`match_${year(s)}_${s.league.round}_${league}_${aId}_${bId}`,year:year(s),round:s.league.round,stage,league,a:aId,b:bId,aName:a.name,bName:b.name,score:[0,0],plays:[],players:[],lineups:rosters.map((r,j)=>r.map((w,i)=>w?{id:w.id,name:w.name,number:teams[j].id==='player'?w.jersey:teams[j].roster.indexOf(w)+1,position:i}:null)),time:s.time};
 const valid=rosters.map(r=>r.filter(Boolean).length===5);const records=rosters.map(r=>r.map(w=>w?{id:w.id,name:w.name,goals:0,assists:0,blocks:0,steals:0,fouls:0}:null));
 if(!valid[0]||!valid[1]){m.forfeit=true;m.score=valid[0]?[5,0]:valid[1]?[0,5]:[0,0];m.plays.push({text:!valid[0]&&!valid[1]?'Neither academy fields five eligible wizards. The fixture is awarded by disciplinary draw.':`${teams[valid[0]?1:0].name} cannot field five eligible wizards. Forfeit.`,score:m.score.slice(),side:valid[0]?0:1});}
 else {const possessions=36+tac.filter(t=>t.tempo==='Fast').length*6-tac.filter(t=>t.tempo==='Slow').length*4;for(let n=0;n<possessions;n++){const side=n%2,opp=1-side,att=ratings[side],def=ratings[opp],t=tac[side],ot=tac[opp];const striker=integer(s,0,1),controller=rosters[side][2],shooter=rosters[side][striker],guardIndex=integer(s,3,4);const offense=(att[striker]*.55+att[2]*.45)*(t.focus==='Offensive'?1.12:t.focus==='Defensive'?.94:1)*(t.tempo==='Fast'?1.06:1),defense=(def[3]+def[4])*.5*(ot.focus==='Defensive'?1.14:ot.focus==='Offensive'?.94:1);const stealChance=t.passing==='Risky'?.2:t.passing==='Safe'?.07:.12;
 let text,kind='block';if(rnd(s)<stealChance){kind='steal';records[opp][guardIndex].steals++;text=`${rosters[opp][guardIndex].name} cuts across the aperture and steals the mote.`;}
 else if(rnd(s)<.035){kind='foul';records[side][striker].fouls++;text=`${shooter.name} is penalized for ${pick(s,['unauthorized gravity','an argumentative familiar','excessive dramatic smoke','a fourth-dimensional elbow'])}.`;}
 else if(rnd(s)<Math.max(.12,Math.min(.86,offense/(offense+defense)*.9))){kind='goal';const points=t.passing==='Risky'&&rnd(s)<.35?2:1;m.score[side]+=points;records[side][striker].goals+=points;records[side][2].assists++;text=`${controller.name} ${pick(s,['threads a pass to','bends the mote toward','opens a rift for'])} ${shooter.name} — ${points===2?'a two-point long aperture!':'through the aperture!'}`;}
 else{records[opp][guardIndex].blocks++;text=`${rosters[opp][guardIndex].name} ${pick(s,['folds a ward over the aperture.','turns the shot into harmless sparks.','reads the feint. No score.'])}`;}
 m.plays.push({text,score:m.score.slice(),side,kind,shooter:striker,guard:guardIndex,actor:shooter.name,momentum:Math.round(100*offense/(offense+defense))});}
 }
 if(m.score[0]===m.score[1]){const side=rnd(s)<.5?0:1;m.score[side]++;m.plays.push({text:`${teams[side].name} wins the sudden-aperture tiebreak.`,score:m.score.slice(),side});}
 const winner=m.score[0]>m.score[1]?0:1;m.winner=teams[winner].id;m.loser=teams[1-winner].id;
 teams.forEach((t,j)=>{t.career.wins+=j===winner?1:0;t.career.losses+=j!==winner?1:0;t.career.pf+=m.score[j];t.career.pa+=m.score[1-j];if(stage==='regular'){const tb=s.league.tables[t.id];tb.w+=j===winner?1:0;tb.l+=j!==winner?1:0;tb.pf+=m.score[j];tb.pa+=m.score[1-j];}
 rosters[j].forEach((w,i)=>{if(!w||!valid[j])return;const r=records[j][i];r.number=m.lineups[j][i].number;r.position=i;r.team=t.id;r.rating=ratings[j][i];r.appearances=1;r.wins=j===winner?1:0;m.players.push(r);for(const key of ['appearances','wins','goals','assists','blocks','steals','fouls']){if(t.id==='player'){if(['appearances','wins'].includes(key)){w.stats[key]=(w.stats[key]||0)+r[key];w.yearStats[key]=(w.yearStats[key]||0)+r[key];}else stat(s,w,key,r[key]);}else w.stats[key]=(w.stats[key]||0)+r[key];}gainXP(s,w,16,true);const sr=s.league.seasonPlayers[w.id]||(s.league.seasonPlayers[w.id]={id:w.id,name:w.name,team:t.id,league:t.league,goals:0,assists:0,blocks:0,steals:0,appearances:0,wins:0});for(const key of ['goals','assists','blocks','steals','appearances','wins'])sr[key]+=r[key];for(const key of ['goals','assists','blocks','steals','appearances','wins']){const boards=s.league.records||(s.league.records={}),board=boards[key]||(boards[key]=[]);const idx=board.findIndex(x=>x.id===w.id);if(idx>=0)board.splice(idx,1);board.push({id:w.id,name:w.name,team:t.id,value:w.stats[key]||0});board.sort((a,b)=>b.value-a.value);board.length=Math.min(50,board.length);}if(t.id==='player')refreshRecords(s,w);});});
 if(playerSide>=0){stat(s,null,'appearances');if(winner===playerSide)stat(s,null,'wins');const opp=teams[1-playerSide];const h=s.league.headToHead[opp.id]||(s.league.headToHead[opp.id]={wins:0,losses:0,pf:0,pa:0});h.wins+=winner===playerSide?1:0;h.losses+=winner!==playerSide?1:0;h.pf+=m.score[playerSide];h.pa+=m.score[1-playerSide];s.league.streak=winner===playerSide?Math.max(0,s.league.streak)+1:Math.min(0,s.league.streak)-1;if(winner===playerSide){s.gold+=35+playerSchool(s).league*25;s.prestige+=1;}news(s,`Arcane Rift: ${a.name} ${m.score[0]}–${m.score[1]} ${b.name}${m.forfeit?' (forfeit)':''}.`,'sport');m.quote=winner===playerSide?`${opp.name}: “A performance worthy of our attention. Until next time.”`:`${opp.name}: “${opp.quote}”`;s.league.lastMatch=clone(m);if(valid[playerSide]&&rnd(s)<.045){const w=pick(s,rosters[playerSide]);w.injury={name:'rift collision',until:s.time+1200000};news(s,`${w.name} suffers a minor Rift collision. Twenty minutes of supervised grumbling.`,'injury');}}
 archive(s,'matches',m.id,m);s.league.matches.push({id:m.id,a:m.a,b:m.b,score:m.score,winner:m.winner,stage,league});return m;
}
export function playRound(s){const l=s.league,r=l.round;for(let league=0;league<4;league++){if(r<14){const ids=l.schools.filter(t=>t.league===league).map(t=>t.id);for(const [a,b] of pairs(ids,r))simulateMatch(s,a,b,'regular',league);}else if(r===14){const table=standings(s,league);const m1=simulateMatch(s,table[0].id,table[3].id,'semifinal',league),m2=simulateMatch(s,table[1].id,table[2].id,'semifinal',league);l.playoffs[league]={regularChampion:table[0].id,seeds:table.slice(0,4).map(t=>t.id),semis:[m1.id,m2.id],finalists:[m1.winner,m2.winner]};}else if(r===15){const p=l.playoffs[league],m=simulateMatch(s,...p.finalists,'final',league);p.final=m.id;p.champion=m.winner;const t=l.schools.find(t=>t.id===m.winner);t.titles++;for(const w of athletes(s,t).filter(Boolean)){if(t.id==='player'){w.stats.championships=(w.stats.championships||0)+1;markWielder(s,w,'riftTitles');w.yearStats.championships=(w.yearStats.championships||0)+1;refreshRecords(s,w);}else w.stats.championships=(w.stats.championships||0)+1;}if(t.id==='player'){stat(s,null,'championships');s.prestige+=12+league*8;recordReputation(s,'Rift',5+league*3);s.gold+=250+league*250;news(s,`${s.name} are ${LEAGUES[league]} champions!`,'championship');}}}l.round++;}
export function endSeason(s){const l=s.league;while(l.round<16)playRound(s);const moves=[],old=Object.fromEntries(l.schools.map(t=>[t.id,t.league]));for(let tier=0;tier<3;tier++){const up=l.playoffs[tier].champion,down=standings(s,tier+1).at(-1).id;moves.push({id:up,from:tier,to:tier+1},{id:down,from:tier+1,to:tier});}
 const leaders=Object.values(l.seasonPlayers).sort((a,b)=>b.goals-a.goals),award=leaders[0]||null;
 archive(s,'seasons',`season_${String(l.year).padStart(6,'0')}`,{id:`season_${l.year}`,year:l.year,tables:clone(l.tables),playoffs:clone(l.playoffs),matches:clone(l.matches),moves,players:clone(l.seasonPlayers),award,rosters:l.schools.map(t=>({id:t.id,name:t.name,league:old[t.id],titles:t.titles,roster:(t.id==='player'?active(s):t.roster).map(w=>({id:w.id,name:w.name,age:age(s,w),sportLevel:w.sportLevel,stats:clone(w.stats)}))}))});
 for(const m of moves){const t=l.schools.find(t=>t.id===m.id);t.league=m.to;if(t.id==='player')news(s,`${m.to>m.from?'Promoted':'Relegated'} to ${LEAGUES[m.to]}. A new chapter begins.`,'sport');}
 for(const t of l.schools.filter(t=>t.id!=='player')){for(const w of t.roster){if(age(s,w)>=w.retireAt){archive(s,'athletes',w.id,{...w,school:t.id,schoolName:t.name,status:'Retired',retiredYear:l.year});w.status='Retired';}}t.roster=t.roster.filter(w=>w.status==='Active');while(t.roster.length<7){const w=wizard(s,true,t.league);t.roster.push(w);}}
 l.year++;l.round=0;l.matches=[];l.playoffs={};l.seasonPlayers={};resetTables(s);
}
