import assert from 'node:assert/strict';
import {DAY,HOUR,FAMILIES} from './data.js';
import * as M from './model.js';
import * as C from './combat.js';
import * as L from './sports.js';
import * as T from './simulation.js';
let passed=0;const test=(name,fn)=>{fn();passed++;console.log('PASS',name);};
function game(seed=123){const s=M.makeGame('Test Academy',1000000,seed);L.createLeague(s);M.openFoundation(s);for(const w of s.applicants.slice(0,5))M.recruit(s,w.id);s.lineup=s.wizards.map(w=>w.id);s.rooms.rift=1;return s;}
function finish(s){for(let i=0;i<900&&s.combat?.state==='fighting';i++)C.stepCombat(s,.25);}
test('Foundation starts empty; capacity is five; applicant recovery pool persists',()=>{const s=M.makeGame('Empty',0,1);assert.equal(s.wizards.length,0);M.openFoundation(s);assert.equal(M.capacity(s),5);assert.equal(s.applicants.length,5);});
test('Recruitment respects capacity and persistent identities',()=>{const s=game();assert.equal(s.wizards.length,5);assert.equal(new Set(s.wizards.map(w=>w.id)).size,5);M.applicants(s);assert.throws(()=>M.recruit(s,s.applicants[0].id));});
test('Offline cap, idempotency, rollback guard, and production',()=>{const s=game();s.rooms.runes=1;s.wizards[0].job='blank';const initial=s.blanks;const r=T.processTime(s,s.lastWall+24*HOUR);assert.equal(r.elapsed,12*HOUR);assert.equal(s.time,12*HOUR);assert.ok(s.blanks>initial);const before=JSON.stringify(s);T.processTime(s,s.lastWall);assert.equal(JSON.stringify(s),before);T.processTime(s,s.lastWall-1000);assert.equal(s.time,12*HOUR);assert.equal(s.depth,0);});
test('New floors stop, and unknown floors cannot be automated',()=>{const s=game();assert.throws(()=>C.startExpedition(s,s.wizards.slice(0,3).map(w=>w.id),1,true));C.startExpedition(s,s.wizards.slice(0,3).map(w=>w.id),1);if(s.combat.state==='choice')C.roomChoice(s,'safe');finish(s);assert.equal(s.combat.state,'victory');assert.equal(s.depth,1);const floor=s.expedition.floor;for(let i=0;i<100;i++)C.stepCombat(s,.5);assert.equal(s.expedition.floor,floor);});
test('Boss attempts require and consume seals once',()=>{const s=game();s.depth=9;s.seals=0;assert.throws(()=>C.startExpedition(s,s.wizards.slice(0,3).map(w=>w.id),10));s.seals=1;C.startExpedition(s,s.wizards.slice(0,3).map(w=>w.id),10);assert.equal(s.seals,0);assert.throws(()=>C.enterFloor(s,10));assert.equal(s.seals,0);});
test('Equipment defines roles; charges and mana constrain spells',()=>{const s=game();const w=s.wizards[0],i=M.item(s,1);i.family='necromancy';i.slot='focus';M.equip(s,w,i.id);s.runes.necromancy=12;C.startExpedition(s,s.wizards.slice(0,3).map(w=>w.id),1);if(s.combat.state==='choice')C.roomChoice(s,'risk');for(let t=0;t<10;t++)C.stepCombat(s,.25);assert.ok(w.stats.summons>=1);assert.ok(s.runes.necromancy<12);assert.ok(s.combat.heroes[0].mana<s.combat.heroes[0].maxMana);});
test('Wipe is permanent and recovery restores exact item identities',()=>{const s=game();s.depth=99;s.seals=1;const ws=s.wizards.slice(0,3),i=M.item(s,1);M.equip(s,ws[0],i.id);C.startExpedition(s,ws.map(w=>w.id),100);finish(s);assert.equal(s.combat.state,'defeat');assert.ok(ws.every(w=>w.status==='Deceased'));assert.equal(s.expedition,null);assert.equal(s.lost.length,1);assert.ok(!s.items.some(x=>x.id===i.id));C.recoverCache(s,s.lost[0]);assert.equal(s.lost.length,0);assert.ok(s.items.some(x=>x.id===i.id));assert.ok(ws.every(w=>w.status==='Deceased'));});
test('A season has 14 regular games per school and exact promotions',()=>{const s=game();for(let r=0;r<16;r++)L.playRound(s);for(const t of Object.values(s.league.tables))assert.equal(t.w+t.l,14);const before=Object.fromEntries(s.league.schools.map(t=>[t.id,t.league]));const champions=Object.values(s.league.playoffs).map(p=>p.champion);L.endSeason(s);for(let l=0;l<4;l++)assert.equal(s.league.schools.filter(t=>t.league===l).length,8);const moved=s.league.schools.filter(t=>t.league!==before[t.id]);assert.equal(moved.length,6);for(let l=0;l<3;l++)assert.equal(s.league.schools.find(t=>t.id===champions[l]).league,l+1);const season=s.pending['seasons/season_000001'].data;assert.equal(season.matches.length,236);assert.equal(season.rosters.length,32);assert.ok(season.players);});
test('Offline matches are identical after save/resume',()=>{const a=game(555),b=M.clone(a);T.processTime(a,a.lastWall+6*HOUR);T.processTime(b,b.lastWall+3*HOUR);const c=M.clone(b);T.processTime(c,c.lastWall+3*HOUR);assert.deepEqual(a.league.tables,c.league.tables);});
test('Aging creates faculty candidates and permanent death records',()=>{const s=game();const w=s.wizards[0];w.startAge=w.retireAt;T.processTime(s,s.lastWall+60000);assert.equal(w.status,'Retired');s.faculty.training=w.id;w.status='Faculty';w.startAge=w.deathAt;T.processTime(s,s.lastWall+60000);assert.equal(w.status,'Deceased');assert.ok(s.pending['wizards/'+w.id]);assert.equal(s.faculty.training,undefined);});
test('Tail distribution produces exceptional rolls without a max-roll field',()=>{const s=game(998);const rolls=Array.from({length:100000},()=>M.roll(s));assert.ok(Math.max(...rolls)>2.3);assert.ok(rolls.every(Number.isFinite));assert.ok(rolls.filter(x=>x>.78&&x<1.4).length>75000);const it=M.item(s,200,true);assert.equal(it.maxRoll,undefined);assert.ok(it.power>0);});
test('Century-scale league and wizard history stays external to live state',()=>{const s=game(772);let years=0,archives=0;for(let i=0;i<202;i++){T.processTime(s,s.lastWall+12*HOUR);for(const v of Object.values(s.pending)){archives++;if(v.type==='seasons')years++;}s.pending={};}assert.equal(M.year(s),102);assert.equal(years,101);assert.ok(archives>24000);assert.equal(s.league.schools.length,32);assert.ok(s.league.schools.every(t=>t.roster.length===7||t.id==='player'));const bytes=JSON.stringify(s).length;console.log('Live save after 101 years:',bytes,'bytes;',archives,'archive writes');assert.ok(bytes<850000);});
test('Hundreds of items are shelved without destruction',()=>{const s=game();for(let i=0;i<450;i++)M.item(s,50,true);assert.equal(s.items.length,180);const saved=Object.values(s.pending).filter(a=>a.type==='items');assert.equal(saved.length,450);assert.equal(saved.filter(a=>a.data.vault).length,270);});
test('League wins and championships count teams once, not five times',()=>{const s=game(222);for(let r=0;r<16;r++)L.playRound(s);const wins=s.league.matches.filter(m=>m.winner==='player').length;assert.equal(s.stats.wins||0,wins);const titles=Object.values(s.league.playoffs).filter(p=>p.champion==='player').length;assert.equal(s.stats.championships||0,titles);});
test('Manual expedition combat survives serialization with identical outcome',()=>{const a=game(1212);C.startExpedition(a,a.wizards.slice(0,3).map(w=>w.id),1);if(a.combat.state==='choice')C.roomChoice(a,'risk');for(let i=0;i<5;i++)C.stepCombat(a,.25);const b=M.clone(a);finish(a);finish(b);assert.deepEqual(a.combat,b.combat);assert.equal(a.gold,b.gold);assert.deepEqual(a.items,b.items);});
console.log(`\n${passed} simulation tests passed.`);
