const active=s=>s.wizards.filter(w=>w.status==='Active');
export const MISSIONS=[
 {id:'doors',title:'Sign the charter',room:'desk',tab:'applicants',text:'Open the academy using the gold button on the grounds. Your first rooms and applicant pool will appear.',goal:s=>!!s.intro,gold:15},
 {id:'five',title:'Meet your founding generation',room:'desk',tab:'applicants',text:'Offer places to five applicants. Recruitment is free. If you lose wizards later, Emergency Admissions can rebuild you to five.',goal:s=>(s.stats.recruited||0)>=5,gold:20},
 {id:'practice',title:'Give someone a job',room:'training',text:'Open the Practice Hall. Tap Adventure training, select a wizard, then Apply. Equipment supplies spells; training grows the wizard behind them.',goal:s=>s.wizards.some(w=>w.job==='training'||(w.stats.training||0)>0),gold:20},
 {id:'blank',title:'Start the rune workshop',room:'runes',text:'Open the Rune Chamber. Tap Make unscribed runes, select a worker, and Apply. Workers on the same recipe share one faster batch.',goal:s=>s.wizards.some(w=>w.job==='blank'),gold:20},
 {id:'scribe',title:'Inscribe your first magic',room:'runes',text:'Tap Inscribe beside Ember (or another family), choose Tier I, and select a wizard. Keep another wizard making blanks if possible.',goal:s=>s.wizards.some(w=>['fire','frost','storm','restoration','necromancy','arcane','nature','shadow','radiant','barrier'].includes(w.job)),gold:15},
 {id:'charges',title:'Let the workshop finish',room:'runes',text:'Watch a shared inscription bar complete. One unscribed rune becomes 12 charges. Matching equipment will use these; Magic Missile needs none.',goal:s=>Object.values(s.runes).some(n=>n>=12),gold:15},
 {id:'party',title:'Prepare three volunteers',room:'gate',text:'At Belowstairs, add three healthy wizards to your party. Prepare lets you choose Front/Middle/Back and a directive. You can begin with Magic Missile and no equipment.',goal:s=>(s.expedition?.ids.length||s.party.length)>=3,gold:10},
 {id:'floor',title:'Take the first stair',room:'gate',text:'Enter floor 1 and watch your party fight automatically. Some rooms offer choices. A cleared new floor always stops; defeated wizards die permanently.',goal:s=>s.depth>=1,gold:25},
 {id:'home',title:'Bring them home',room:'gate',text:'After clearing a floor, choose Return to Academy. HP and mana persist downstairs, so coming home is often the clever choice. Recover before going deeper.',goal:s=>s.depth>=1&&!s.expedition,gold:15},
 {id:'rift',title:'Open your Rift program',room:'rift',tab:'lineup',text:'Open Arcane Rift. These are the same academy wizards, with separate sport levels and natural talent. Ordinary academy work does not prevent match participation.',goal:s=>!!s.rooms.rift,gold:20},
 {id:'lineup',title:'Field your first five',room:'rift',tab:'lineup',text:'Choose two Strikers, a Controller, and two Wardens. Assign jersey numbers and tactics. Configure reserves when you have them: an incomplete eligible team forfeits.',goal:s=>!!s.rooms.rift&&new Set(s.lineup.filter(id=>active(s).some(w=>w.id===id&&!w.injury)&&!s.expedition?.ids.includes(id))).size===5,gold:25}
];
export const SIDE_MISSIONS=[
 {id:'equipment',title:'Make a wizard’s first build',room:'storage',tab:'items',text:'Find equipment in the dungeon. Tap its tile in the Strongroom, choose a wizard, compare, and equip. Supply that item’s rune family and tier. Loot is random—this can wait.',goal:s=>s.wizards.some(w=>Object.values(w.equipment).some(Boolean)),gold:20},
 {id:'sport',title:'Your first matchday',room:'rift',tab:'watch',text:'The countdown at the top shows the next scheduled match. Keep five eligible players configured, then visit Match Theatre to watch the recording. You do not need to stay online.',goal:s=>(s.stats.appearances||0)>0,gold:20},
 {id:'seal',title:'Prepare for the tenth floor',room:'runes',text:'Assign a wizard to Bind Boss Seals. Each batch uses 3 seal ingredients and 8 gold. Every boss attempt—including the first—requires a seal.',goal:s=>(s.stats.seals||0)>0,gold:15}
];
export function updateTutorial(s){s.tutorial??={done:[],claimed:[],hidden:false};for(const m of [...MISSIONS,...SIDE_MISSIONS])if(!s.tutorial.done.includes(m.id)&&m.goal(s))s.tutorial.done.push(m.id);return s.tutorial;}
export function currentMission(s){return MISSIONS.find(m=>!s.tutorial?.claimed.includes(m.id))||null;}
export function claimMission(s,id){const q=updateTutorial(s),m=[...MISSIONS,...SIDE_MISSIONS].find(m=>m.id===id);if(!m||!q.done.includes(id)||q.claimed.includes(id))return false;if(MISSIONS.includes(m)&&currentMission(s)?.id!==id)return false;q.claimed.push(id);s.gold+=m.gold;return true;}
