import fs from 'node:fs/promises';
import * as M from './model.js';import * as L from './sports.js';import * as T from './simulation.js';import * as C from './combat.js';import {ROOMS} from './data.js';
const nodes=new Map();function node(){return {innerHTML:'',textContent:'',open:false,classList:{add(){},remove(){}},addEventListener(){},showModal(){this.open=true;},close(){this.open=false;},querySelector(){return null;},getBoundingClientRect(){return {left:0,top:0,right:900,bottom:900}}};}
globalThis.document={getElementById(id){if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);},addEventListener(){},hidden:false};globalThis.window={addEventListener(){}};globalThis.localStorage={getItem(){return null},setItem(){},removeItem(){}};globalThis.setInterval=()=>0;
let source=await fs.readFile('./app.js','utf8');source=source.replaceAll("from './","from './").replace(/\nboot\(\);\s*$/,`\nexport function fixture(state){s=state;} export function renderForTest(r){route=r;renderPanel();return document.getElementById('panel-body').innerHTML;} export {renderMain,renderMatch,showReport,renderSeason};`);await fs.writeFile('./app-under-test.mjs',source);
const app=await import('./app-under-test.mjs');const s=M.makeGame('UI & <test>',0,999);L.createLeague(s);M.openFoundation(s);s.gold=100000;s.prestige=10000;for(const room of ROOMS)s.rooms[room.id]=1;for(const w of s.applicants.slice(0,5))M.recruit(s,w.id);s.lineup=s.wizards.map(w=>w.id);s.depth=30;for(let i=0;i<20;i++)M.item(s,25,true,s.wizards[0]);app.fixture(s);app.renderMain();let count=0;const cases={desk:['applicants','office','events','settings','guide'],dorm:['roster'],storage:['items','supplies','records'],training:['main'],runes:['main'],infirmary:['main'],gate:['main'],rift:['league','lineup','watch','schools','playoffs','records'],archives:['records','seasons'],hall:['achievements'],garden:['main'],observatory:['main']};
for(const [id,tabs] of Object.entries(cases))for(const tab of tabs){const html=app.renderForTest({type:'room',id,tab});if(!html)throw Error('Empty '+id+tab);count++;}
app.renderForTest({type:'wizard',id:s.wizards[0].id});app.renderForTest({type:'item',id:s.items[0].id});T.createEvent(s);app.renderForTest({type:'events'});s.depth=0;C.startExpedition(s,s.wizards.slice(0,3).map(w=>w.id),1);app.renderForTest({type:'combat'});if(s.combat.state==='choice')C.roomChoice(s,'safe');for(let i=0;i<300;i++)C.stepCombat(s,.5);app.renderForTest({type:'combat'});for(let r=0;r<16;r++)L.playRound(s);app.renderForTest({type:'match',match:s.league.lastMatch});L.endSeason(s);app.renderForTest({type:'season',season:s.pending['seasons/season_000001'].data});app.showReport({elapsed:3600000,capped:false,gold:5,blanks:2,seals:1,potions:1,runes:4,levels:1,events:s.feed.slice(0,3)});
console.log('PASS',count,'management panels, wizard/item details, event decisions, combat states, match replay, season history, and offline summary render without exceptions.');console.log('PASS Academy name escapes user-supplied markup:',document.getElementById('app').innerHTML.includes('&lt;test&gt;'));
await fs.unlink('./app-under-test.mjs');
