import fs from 'node:fs/promises';
import {startDuel,stepDuel} from './duels.js';import * as M from './model.js';import * as L from './sports.js';import * as T from './simulation.js';import * as C from './combat.js';import {ROOMS} from './data.js';
const nodes=new Map();function node(){return {innerHTML:'',textContent:'',open:false,classList:{add(){},remove(){}},addEventListener(){},showModal(){this.open=true;},close(){this.open=false;},querySelector(){return null;},getBoundingClientRect(){return {left:0,top:0,right:900,bottom:900}}};}
globalThis.document={getElementById(id){if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);},addEventListener(){},hidden:false};globalThis.window={addEventListener(){}};globalThis.localStorage={getItem(){return null},setItem(){},removeItem(){}};globalThis.setInterval=()=>0;
let source=await fs.readFile('./app.js','utf8');source=source.replaceAll("from './","from './").replace(/\nboot\(\);\s*$/,`\nexport function fixture(state){s=state;} export function renderForTest(r){route=r;renderPanel();return document.getElementById('panel-body').innerHTML;} export {renderMain,renderMatch,showReport,renderSeason};`);await fs.writeFile('./app-under-test.mjs',source);
const app=await import('./app-under-test.mjs');const s=M.makeGame('UI & <test>',0,999);L.createLeague(s);M.openFoundation(s);s.gold=100000;s.prestige=10000;for(const room of ROOMS)s.rooms[room.id]=1;for(const w of s.applicants.slice(0,5))M.recruit(s,w.id);s.lineup=s.wizards.map(w=>w.id);s.depth=30;for(let i=0;i<20;i++)M.item(s,25,true,s.wizards[0]);app.fixture(s);app.renderMain();let count=0;const cases={desk:['applicants','office','events','settings','guide'],dorm:['roster'],storage:['items','supplies','records'],training:['main'],runes:['main'],infirmary:['main'],gate:['main'],rift:['league','lineup','watch','schools','playoffs','records'],archives:['records','seasons'],hall:['achievements'],garden:['main'],observatory:['main']};
for(const [id,tabs] of Object.entries(cases))for(const tab of tabs){const html=app.renderForTest({type:'room',id,tab});if(!html)throw Error('Empty '+id+tab);count++;}
s.wizards[0].job='fire';s.wizards[1].job='fire';s.wizards[2].job='training';
const room=app.renderForTest({type:'room',id:'runes',tab:'main'});if(room.includes(s.wizards[2].name))throw Error('Rune chamber leaks unrelated worker');if((room.match(/data-production="fire:1"/g)||[]).length!==1)throw Error('Expected one shared Ember action');if(!room.includes('Inscribe'))throw Error('Missing recipe action');
const picker=app.renderForTest({type:'workers',job:'fire',tier:1,selected:[s.wizards[0].id],parent:{type:'room',id:'runes',tab:'main'}});if(!picker.includes(s.wizards[2].name)||!picker.includes('Adventure training'))throw Error('Picker must show all current jobs');
const dorm=app.renderForTest({type:'room',id:'dorm',tab:'roster'});if(!dorm.includes(s.wizards[2].name))throw Error('Dorm must retain full overview');
console.log('PASS Room-local shared actions, recipe button, all-wizard picker, and full dorm overview.');
const highlights=app.renderForTest({type:'highlights'});if(!highlights.includes('DISCOVERY'))throw Error('Missing item reveal');
const club=app.renderForTest({type:'duel'});if(!club.includes('Percival Paperhat')||!club.includes('Challenge'))throw Error('Missing duel ladder');
startDuel(s,s.wizards[0].id,0);let duelHTML=app.renderForTest({type:'duel',bout:true});if(!duelHTML.includes('combat-canvas'))throw Error('Missing duel arena');s.duel.run.combat.heroes[0].power=10000;while(!s.duel.finished)stepDuel(s,.25);duelHTML=app.renderForTest({type:'duel',bout:true});if(!duelHTML.includes('First victory'))throw Error('Missing duel reward');
console.log('PASS loot reveals, duel ladder, live canvas panel, and first-win reward panel.');
const install=app.renderForTest({type:'install'});if(!install.includes('Add to Home Screen')||!install.includes('Install app'))throw Error('Missing installation instructions');
const profile=app.renderForTest({type:'wizard',id:s.wizards[0].id});if((profile.match(/data-act="equipment-slot"/g)||[]).length!==3)throw Error('Expected three tappable slots');
if(profile.indexOf('Choose &amp; compare equipment')<0&&profile.indexOf('Choose & compare equipment')<0)throw Error('Missing equipment priority');if(profile.indexOf('Headmaster’s tags')>profile.indexOf('Work & expedition behavior'))throw Error('Tags buried after work controls');if(!app.renderForTest({type:'room',id:'rift',tab:'lineup'}).includes('Set best lineup'))throw Error('Missing lineup action');
const choice=s.items.find(i=>i.slot==='focus');if(!choice)throw Error('Fixture lacks focus');
const slot=app.renderForTest({type:'equipment-slot',wizard:s.wizards[0].id,slot:'focus',preview:choice.id});if(!slot.includes('Whole-wizard totals')||!slot.includes('SELECTED ITEM')||!slot.includes('data-act="slot-equip"'))throw Error('Missing selected comparison');
const detail=app.renderForTest({type:'item',id:choice.id,target:s.wizards[0].id,slotParent:{type:'equipment-slot',wizard:s.wizards[0].id,slot:'focus'}});if(!detail.includes('Back to slot comparison'))throw Error('Lost slot return path');
console.log('PASS installation help, three tappable profile slots, candidate stat/whole-build comparison, and details return path.');
const missionPanel=app.renderForTest({type:'tutorial'});if(!missionPanel.includes('Sign the charter')||!missionPanel.includes('optional'))throw Error('Tutorial journal missing missions');
app.renderForTest({type:'wizard',id:s.wizards[0].id});app.renderForTest({type:'item',id:s.items[0].id});T.createEvent(s);app.renderForTest({type:'events'});s.depth=0;C.startExpedition(s,s.wizards.slice(0,3).map(w=>w.id),1);app.renderForTest({type:'combat'});if(s.combat.state==='choice')C.roomChoice(s,'safe');for(let i=0;i<300;i++)C.stepCombat(s,.5);app.renderForTest({type:'combat'});for(let r=0;r<16;r++)L.playRound(s);app.renderForTest({type:'match',match:s.league.lastMatch});L.endSeason(s);app.renderForTest({type:'season',season:s.pending['seasons/season_000001'].data});app.showReport({elapsed:3600000,capped:false,gold:5,blanks:2,seals:1,potions:1,runes:4,levels:1,events:s.feed.slice(0,3)});
console.log('PASS',count,'management panels, wizard/item details, event decisions, combat states, match replay, season history, and offline summary render without exceptions.');console.log('PASS Academy name escapes user-supplied markup:',document.getElementById('app').innerHTML.includes('&lt;test&gt;'));
await fs.unlink('./app-under-test.mjs');
